### ISSUE TITLE
onFulfill doesn't get fired

### ISSUE THREAD

**Issue by hengvenchang** [retyui/react-native-confirmation-code-field#102]
Amazing library so far! but when i try to use onFulfill props, it doesn't got called

<img width="897" alt="Screenshot 2020-02-06 at 1 39 35 PM" src="https://user-images.githubusercontent.com/17307495/73912087-38bfe700-48e6-11ea-9c37-86f967187216.png">

**Comment by retyui** [comment]
`blurOnSubmit`, `onFullfill` - are deprecated and removed props

You should use own `onChangeText` handler:

```js
onChangeText={text => {
  if(text.length === CELL_COUTN){
     Alert.alert('onFullfill');
  }
}}
```

**Comment by hengvenchang** [comment]
ohhhh! Thank you sir
