### ISSUE TITLE
Border Input Color Styles not applied for Component inside Codefield for iOS but they do appear on Android

### ISSUE THREAD

**Issue by MFRamon** [retyui/react-native-confirmation-code-field#107]
I've added a border color for when focusing on a Text Component inside a CodeField component ,these styles do apply for when running the app on Android but the same styles are not applied on iOS.

This is how it looks on both platforms : 

iOS : 
![Screen Shot 2020-02-14 at 10 25 04](https://user-images.githubusercontent.com/25883970/74548905-4bed3b00-4f14-11ea-92f1-267af3f274b3.png)

Android  : 
![Screen Shot 2020-02-14 at 10 24 54](https://user-images.githubusercontent.com/25883970/74548916-53144900-4f14-11ea-96dd-616def909993.png)

react-native version :  "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
package version :  "react-native-confirmation-code-field": "^5.1.0",

**Comment by retyui** [comment]
Dublicate

https://github.com/retyui/react-native-confirmation-code-field/issues/101

**Comment by MFRamon** [comment]
Oh,Thanks I'll give it a look
