### ISSUE TITLE
Showing shadow in code digits text and cursor

### ISSUE THREAD

**Issue by vishgoel007** [retyui/react-native-confirmation-code-field#108]
![code](https://user-images.githubusercontent.com/36643209/74812547-b689e680-5319-11ea-8be8-2094437c5552.png)
See you can see the shadow behind code. How can i remove this?

**Comment by retyui** [comment]
@vishgoel007 
Try to use: 

```js
 renderCell={({index, symbol, isFocused}) => (
       <View key={index} onLayout={getCellOnLayoutHandler(index)}>>   
        <Text
            style={[styles.cell, isFocused && styles.focusCell]}
            {symbol || (isFocused ? <Cursor /> : null)}
          </Text>
       </View>
  )}
```

**Comment by vishgoel007** [comment]
@retyui  How can i automatically focus on first cell when screen (using confirmation code field) is pushed ?
