### ISSUE TITLE
Wrong props

### ISSUE THREAD

**Issue by dudovcic** [retyui/react-native-confirmation-code-field#11]
node_modules/react-native-confirmation-code-field/index.d.ts(36,51): error TS2694: Namespace '".../node_modules/@types/react-native/index"' has no exported member 'TextInputProps'.
node_modules/react-native-confirmation-code-field/index.d.ts(43,34): error TS2694: Namespace '".../node_modules/@types/react-native/index"' has no exported member 'ViewProps'.
10:23:25 - Compilation complete. Watching for file changes.

**Comment by dudovcic** [comment]
PR which fixes it: https://github.com/retyui/react-native-confirmation-code-field/pull/12

**Comment by dudovcic** [comment]
It's actually Props on newer versions of RN.

**Comment by retyui** [comment]
@dudovcic 
What happens ?

**Comment by dudovcic** [comment]
There was a naming change in RN at some point from Properties to Props.
I realised that I'm using an older RN version which has Properties instead of Props.

**Comment by retyui** [comment]
@dudovcic I recomend you use latest RN version `0.57`
