### ISSUE TITLE
is the onFulfill hook still available in ver 5?

### ISSUE THREAD

**Issue by emclab** [retyui/react-native-confirmation-code-field#111]
My app used ver 4 and after upgrade to ver 5, the module stopped working. Is the onFulfill hook still available in ver 5? I didn't find it in the doc and the examples. Thanks.

**Comment by retyui** [comment]
Do you mean that you change cellCount dynamically? and after that something will broke ?

**Comment by KDederichs** [comment]
He's probably looking for the 'onFulfill' callback that gets called when you have entered all of the code.
I'm wondering if that's gone as well, cause it's really useful for sending the input of the code fields to be validated

**Comment by retyui** [comment]
it can be easily simulated in new the version:
```
const CELL_COUNT = 6;

<CodeField
        cellCount={CELL_COUNT}
        onChangeText={(value) => {
          if(value.length === CELL_COUNT){
            onFulfill(value);
          }
        }}
/>
```
