### ISSUE TITLE
TypeError using React Native v0.62.0

### ISSUE THREAD

**Issue by Saranchenkov** [retyui/react-native-confirmation-code-field#114]
I'm trying to migrate to react native 0.62.0 and see the following error on my screen on app start.
"react-native-confirmation-code-field": "^5.1.0"
"react-native": "0.62.0",

Everything works fine with "react-native": "0.61.5"

![image](https://user-images.githubusercontent.com/25454843/77685700-e4afb580-6fac-11ea-94e0-2e9c7529d9ea.png)

**Comment by retyui** [comment]
Try to use next version

```
yarn add react-native-confirmation-code-field

# for react-native@0.62.x and above
yarn add react-native-confirmation-code-field@next
```

**Comment by retyui** [comment]
@Saranchenkov Was it help? Can I close issue?

**Comment by Saranchenkov** [comment]
@retyui Yes, it works, thanks!
