### ISSUE TITLE
Bug react-native 0.62.0 _reactNative.TextInput is not a constructor

### ISSUE THREAD

**Issue by ryantando** [retyui/react-native-confirmation-code-field#116]
Upgrading react-native to 0.62.0 cause an issue on `TextInputCustom.js 7:5` due to the warning for old RN version

Got: `TypeError: _reactNative.TextInput is not a constructor`

```// $FlowFixMe
if (!new TextInput()._onPress) {
  // eslint-disable-next-line no-console
  console.warn(
    '[react-native-confirmation-code-field]: This version React Native not support hack for TextInput!',
  );
}

**Comment by retyui** [comment]
@ryantando duplicate https://github.com/retyui/react-native-confirmation-code-field/issues/114
