### ISSUE TITLE
Pressing done button on Android number-pad does not dismiss keyboard

### ISSUE THREAD

**Issue by whenmoon** [retyui/react-native-confirmation-code-field#119]
When `keyboardType="number-pad"` on Android and I press the done / tick / continue button on the bottom right of the keyboard, the keyboard does not dismiss. I want to be able to hide the keyboard by pressing this button, as I can do using a normal text input. The only way to dismiss the keyboard is to press the small down facing arrow on the navigation bar at the bottom of the screen.

**Comment by retyui** [comment]
@whenmoon Please try 

```js
import {Keyboard} from 'react-native';

//...

<CodeField
  // ...
  onSubmitEditing={Keyboard.dismiss}
/>
```

**Comment by whenmoon** [comment]
It works! Thank you :)
