### ISSUE TITLE
Issue with Animated

### ISSUE THREAD

**Issue by babyrusa** [retyui/react-native-confirmation-code-field#121]
Hi, I copied the code from Animated example but it has been given a lot of similar errors like this for the animated. Probably different syntax? 
```
Invariant Violation: Outrange cannot include #fff. (#fff, #f7fafe)
```
Wish I could attach images

**Comment by retyui** [comment]
@babyrusa Could you please create a sample demo repo to reproduce this problem?

**Comment by retyui** [comment]
@babyrusa ...
