### ISSUE TITLE
AutoFocus first code field?

### ISSUE THREAD

**Issue by gtwilliams03** [retyui/react-native-confirmation-code-field#124]
I have been trying to figure out how to automatically autoFocus the first digit field for the code field to show the keyboard - but haven't been able to figure this out.  Currently, the user has to tap on the first field to show the keyboard and to start entering input.

Is there a way to do something like the `autoFocus` flag on a `TextInput` field?

**Comment by gtwilliams03** [comment]
Never mind - figured it out - I needed to pass in `autoFocus={true}`and spread the props.  Closing.

**Comment by retyui** [comment]
ok, cool
