### ISSUE TITLE
6.1.0 ref is missing in typescript

### ISSUE THREAD

**Issue by KDederichs** [retyui/react-native-confirmation-code-field#128]
`TS2322: Type '{ value: string; onChangeText: (changeValue: string) => void; cellCount: number; keyboardType: "number-pad"; renderCell: ({ index, symbol, isFocused }: { symbol: string; index: number; isFocused: boolean; }) => ReactElement<any, string | ... 1 more ... | (new (props: any) => Component<...>)>; ref: RefObject<...>; }' is not assignable to type 'IntrinsicAttributes & { rootStyle?: any; textInputStyle?: StyleProp<TextStyle>; RootProps?: {} | undefined; RootComponent?: FunctionComponent<any> | ComponentClass<...> | undefined; cellCount?: number | undefined; renderCell: (options: { ...; }) => ReactElement<...>; } & Pick<...>'.   Property 'ref' does not exist on type 'IntrinsicAttributes & { rootStyle?: any; textInputStyle?: StyleProp<TextStyle>; RootProps?: {} | undefined; RootComponent?: FunctionComponent<any> | ComponentClass<...> | undefined; cellCount?: number | undefined; renderCell: (options: { ...; }) => ReactElement<...>; } & Pick<...>'.`

ref seems to be missing in the type definition released with 6.1.0

**Comment by retyui** [comment]
@KDederichs Thanks, I will fix it immediately

**Comment by retyui** [comment]
@KDederichs Try a new version 6.1.1

**Comment by KDederichs** [comment]
Looks good, thanks a lot!
