### ISSUE TITLE
Expo Web

### ISSUE THREAD

**Issue by sreekanth-14** [retyui/react-native-confirmation-code-field#131]
Does it work on expo web?

**Comment by retyui** [comment]
actually latest version  no(

but 4.x has this opportunity 

https://snack.expo.io/@retyui/demo-for-react-native-confirmation-code-field

**Comment by sreekanth-14** [comment]
Thanks I'm using 4.0.0 right now. I'll give it a try. 
PS: The above snack works fine. Should check in my project too.

**Comment by retyui** [comment]
I will think about adding web support for the latest version

**Comment by retyui** [comment]
I will update expo example to the latest version and seems it work fine

https://snack.expo.io/@retyui/demo-for-react-native-confirmation-code-field
