### ISSUE TITLE
Is there any callback for checking last input?

### ISSUE THREAD

**Issue by crazypioneer** [retyui/react-native-confirmation-code-field#134]
onFulfill={(isValid) => this.onRegist(isValid)}

This is what is did in previous version.
But I can't find proper one on new version.

**Comment by retyui** [comment]
@crazypioneer 

Please check a CHANGELOG file. I described how to emulate this method on new versions

https://github.com/retyui/react-native-confirmation-code-field/blob/master/CHANGELOG.md#500

**Comment by crazypioneer** [comment]
Thank you!
I already did it.
