### ISSUE TITLE
Proposed modification to support spacer elements

### ISSUE THREAD

**Issue by prometheas** [retyui/react-native-confirmation-code-field#135]
My team and I are interested in using this component for numeric inputs of values that include hyphens (e.g., phone number and social security numbers). Would you be open to our attempting a PR for such a feature enhancement, perhaps adding a `formatting` prop that supports the ability to specify character groupings and a separator token.

Is this a feature that feels like a good fit for this component, or would you prefer we fork and go our own way?

**Comment by retyui** [comment]
@prometheas 
I am glad that you use this library!

I designed API of this library to make super flexible and extendable

So it isn't a problem to use it as [masked TextInput](https://github.com/retyui/react-native-confirmation-code-field/tree/master/examples/DemoCodeField/src/FormattingExample)

**Comment by prometheas** [comment]
So, wait. Does that mean you will or will not accept PRs for the proposed use case / feature addition?

**Comment by retyui** [comment]
@prometheas 
PRs Welcome
