### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by adiBinen** [retyui/react-native-confirmation-code-field#137]
Hi,
I'm using an iOS device with RTL support and I have issues with the order of the characters in the code.
First, I typed 1 , 2 , 3 and 4, then I selected the second cell and it deleted the rest of the code as accepted (so now the code is '1'). But when I continue to type, it adds the characters to the start of the string. So when I typed '2', the code was '21', instead of '12'.
In addition, when I delete the characters is stops on the first one so I can't delete it unless I click on that cell.
I attached a video so it will be more clear:

![image](https://im2.ezgif.com/tmp/ezgif-2-b356fb075473.gif)

I'm using React Native 0.61.4, so I have to install the react-native-confirmation-code-field version 5.x.x (I'm using 5.1.0).

How can I fix that?
Is there an option to disable the selection of the cells?

Thank you.

**Comment by retyui** [comment]
I will check this issue, and also I made a new release   now you can use v6 for react-native@0.61.x and below

**Comment by retyui** [comment]
![](https://media.giphy.com/media/hUAFT2kCRE2iku5KwG/giphy.gif)

**Comment by retyui** [comment]
@adiBinen hi hi

**Comment by mohammadrahmanian** [comment]
Hi. I have the same issue. When i'm using the app in RTL mode, code fields start to fill from right to left and it causes the code to mess up. when i'm entering 1-2-3-4-5 the app shows 5-4-3-2-1
![SC](https://user-images.githubusercontent.com/26001660/85952995-6800ee80-b982-11ea-91ec-d3d5e7056fef.jpg)

**Comment by retyui** [comment]
@mohammadrahmanian 

Try to apply the next styles to revert a cell's position 

```diff
<CodeField
+  rootStyle={{
+     flexDirection: 'row-reverse'
+  }}
/>;
```

**Comment by mohammadrahmanian** [comment]
Thanks. It solved my problem.

> @mohammadrahmanian
> 
> Try to apply the next styles to revert a cell's position
> 
> ```diff
> <CodeField
> +  rootStyle={{
> +     flexDirection: 'row-reverse'
> +  }}
> />;
> ```

**Comment by retyui** [comment]
@adiBinen Can I close this issue?

**Comment by anastely** [comment]
@retyui Thanks,
Hey, @mohammadrahmanian  Can you tell me the font name you used in this screen?

**Comment by mohammadrahmanian** [comment]
@anastely of course. it is Futura.
https://www.fonts.com/font/linotype/futura

**Comment by retyui** [comment]
See https://github.com/retyui/react-native-confirmation-code-field/issues/137#issuecomment-651611190

**Comment by mohammadjfadaee** [comment]
thanks bro 😍😍

**Comment by sirramin** [comment]
I used `flexDirection: 'row-reverse'` but still have the problem.
