### ISSUE TITLE
Clear by focus insn't working anymore

### ISSUE THREAD

**Issue by sidbentifraouine** [retyui/react-native-confirmation-code-field#138]
First of all, huge thanks for the good job.

I had this issue on iOS Simulator (11) then I decided to try on your Expo examples: 
![ezgif-1-c45b6743705f](https://user-images.githubusercontent.com/19405039/84292920-52e52c80-ab47-11ea-828f-8692c976952a.gif)

**Comment by retyui** [comment]
@sidbentifraouine 
I create a quick demo with RN "0.61.2" and code field "6.4.0"
and  it works fine 

maybe you faced with an issue that I describe here: https://github.com/retyui/react-native-confirmation-code-field/tree/master/examples/DemoCodeField/src/UnderlineExample#underline-example

if no, could you please show your code

**Comment by retyui** [comment]
@sidbentifraouine hi hi

**Comment by binchik** [comment]
@retyui it didn't work for me either. I digged into the code and found out that `useClearByFocusCell` returns `{onPress}` handler as first param that should be spread into CodeField props which in turn is spread into hidden `TextInput` component's props. But react-native's TextInput doesn't support onPress. So instead of spreading the useClearByFocusCell's props into CodeField component, I used `onTouchStart` it like this:

```
    <CodeField
      ref={ref}
      rootStyle={style}
      autoFocus={autoFocus}
      textContentType="oneTimeCode"
      onTouchStart={codeFieldProps.onPress as any}
      value={value}
      cellCount={cellCount}
      keyboardType="number-pad"
      onChangeText={onChangeValue}
      renderCell={renderCell}
    />
```

https://github.com/facebook/react-native/issues/15570#issuecomment-385439273

**Comment by retyui** [comment]
@binchik 

It is a difficult situation

Because stability of workgroup with onPress depends on

- Platform
- react-native version
- this module version

So can you give me more details?

**Comment by binchik** [comment]
@retyui

I'm on RN 0.62.2. react-native-confirmation-field 6.4.0

`TextInput.onPress` does not work on both iOS and Androd.

`TextInput.onTouchStart`works on iOS. Haven't checked android yet, but in the react-native issue I mentioned, it's mentioned that you have to wrap TextInput in a touchabe component on Android. (The issue is mid 2017 and from what I experience it's still there).

**Comment by retyui** [comment]
`onTouchStart` & `onPress` don't work on Android!

I use a specific workaround to solve this issue [https://github.com/retyui/react-native-confirmation-code-field/blob/master/path-rn-62.js]

**Comment by manuelmhtr** [comment]
For all fogs having the `TypeError: _reactNative.TextInput is not a constructor` error: **Update `react-native-confirmation-code-field` to `^6.5.0`**, that should work.

**Comment by manuelmhtr** [comment]
@retyui you library is amazing, however I had bad times figuring out React Native 0.61 works with code field v5 and React Native 0.62 with code field v6. **You should add this to the documentation**, I think is an important detail.

**Comment by amitv1992** [comment]
I tried Installing "5.1.0" or 5 by doing react-native-confirmation-code-field@5, this feature is not working.
Even i tried  doing, what you said [here](https://github.com/retyui/react-native-confirmation-code-field/tree/master/examples/DemoCodeField/src/UnderlineExample#underline-example)
// GOOD ✔️
renderCell={({index, symbol, isFocused}) => (
  <View
    key={index}
    onLayout={getCellOnLayoutHandler(index)}
  >
    <Text>{...}</Text>
  </View>
)}

Nothing is working so far.

Also the snack demo is not working as expected. Check out > https://snack.expo.io/Zil!jCFft
**I m using "react-native": "~0.61.5"**
any update on this
cc: @sidbentifraouine 
@retyui

**Comment by NRech** [comment]
I am using RN version 0.62.2 (Expo 38) and the version 6.5.0 of the library, and I have the same problem. But it's very weird, first time I installed and created my custom component, everything was working just fine, so out of nowhere, it stopped, on both platforms.
I did not update anything related, just installed some new libraries and booom. 
Weirdly enough, I uninstalled the library and installed again and it's working again. Maybe it gets broken (God knows how) when we install something after? I don't know.

**Comment by retyui** [comment]
@NRech Please try to add a `postinstall` script on `package.json`

```json
{
  "scripts": {
    "postinstall": "node ./node_modules/react-native-confirmation-code-field/path-rn-62.js"
  }
}
```

**Comment by NRech** [comment]
> ```json
> "postinstall": "node ./node_modules/react-native-confirmation-code-field/path-rn-62.js"
> ```

Yes! I think this solved the problem! Any update I'll be posting here!

Thank you so much for your amazing work with this component!

**Comment by jmlavoier** [comment]
I had the same problem. I solved removing my `node_modules` and installing everything again. 

```shell
$ rm -rf node_modules
$ yarn
```

I didn't try to add that "postinstall" running that js. I believe that doing this we don't need to do what I did anymore, do we?

**Comment by kristoff2016** [comment]
Any update?

**Comment by retyui** [comment]
Use the next hack: 
https://github.com/retyui/react-native-confirmation-code-field/issues/138#issuecomment-668737557

**Comment by dinh1997** [comment]
> Use the next hack:
> [#138 (comment)](https://github.com/retyui/react-native-confirmation-code-field/issues/138#issuecomment-668737557)

It don't work for me

**Comment by retyui** [comment]
@dinh1997 Could you please create a demo repo?

**Comment by 2j2e** [comment]
Expo 39, "react-native-confirmation-code-field": "^6.5.0"
Same issue, can't fix it in any way.

**Comment by ThingCoDanW** [comment]
This still appears to be an issue on Android. Have not tested on iOS yet, but it's working on web.

I've set it up as specified in the docs, with the `onLayout={getCellOnLayoutHandler(index)}` on my wrapper view, but no luck.

**Comment by Meycon** [comment]
??

**Comment by seancheung** [comment]
Same here with RN 0.63.4 and version 6.7.0
No idea it worked before.

**Comment by retyui** [comment]
After any install or removing node modules please run `node ./node_modules/react-native-confirmation-code-field/path-rn-62.js`

**Comment by theMasix** [comment]
@retyui It solves the issue, But kinda weird solution and there should be a better (probably a built-in one) solution for it.

**Comment by retyui** [comment]
@theMasix this ugly solution only needs `0.62.x...0.63.x` react-native versions.

I recommend updating your RN version
