### ISSUE TITLE
The last version is not separating cells

### ISSUE THREAD

**Issue by felire** [retyui/react-native-confirmation-code-field#139]
Hi, I installed the last version and it's not separating cells. The field behaviour it's the same if there is or if there isn't `onLayout`. Here is my code:

this is my cell:
```
 <View
      onLayout={onLayout}
      style={[
        styles.cell,
        isFocused && styles.focusCell,
        !!symbol || isFocused ? styles.touched : styles.notTouched,
        error && styles.error,
        success && styles.success
      ]}>
      <CustomText>{symbol || (isFocused ? <Cursor /> : '')}</CustomText>
    </View>
```

And here is an image on how it looks: 

![Screen Shot 2020-06-17 at 10 34 26](https://user-images.githubusercontent.com/11776795/84904853-3769ac80-b086-11ea-96c3-e9e6206d4c0e.png)

I could put the cell margins using index but I wanna know if this is something of the library or I'm implementing it wrong

**Comment by retyui** [comment]
Hi @felire 
Will you try to add a margin for cells?

**Comment by felire** [comment]
yes it works if I add a margin to the cells. But I thought that the library have that behaviour by default.

**Comment by retyui** [comment]
actually no
this is your area of responsibility
