### ISSUE TITLE
Method onFulfill is not getting called upon entering all the codes

### ISSUE THREAD

**Issue by RishavGoswami** [retyui/react-native-confirmation-code-field#141]
I need to call a function when the user is done entering the code. In my case, the user needs to enter 5 code but as soon as he is done entering the 5th code the keyboard gets close and the onFulFill method is not getting called. When does the onFulFill method is called?

Below is the code I use. I want to call a function as soon as the user enters all the code.

```
const handlerOnFulfill = code => console.log(code);

 <CodeField
    ref={ref}
    {...props}
    value={value}
    onChangeText={hanldeSetAccessCode}
    cellCount={CELL_COUNT}
    rootStyle={styles.codeFieldRoot}
    keyboardType="default"
    onFulfill={this.handlerOnFulfill}
    renderCell={({ index, symbol, isFocused }) => (
        <Text
            key={index}
            style={[
                styles.cell,
                isAuthorized && styles.focusCell,
                isFocused && styles.focusCell,
            ]}
            onLayout={getCellOnLayoutHandler(index)}
        >
        {symbol || (isFocused ? <Cursor /> : null)}
        </Text>
    )}
/>
```

**Comment by retyui** [comment]
[`onFulfill` was deprecated, use onChangeText instead of it](https://github.com/retyui/react-native-confirmation-code-field/blob/master/CHANGELOG.md#500)

**Comment by RishavGoswami** [comment]
I've used onChangeText to get the input but, how would I know if the user is done entering all the code? Let's say, I set the cell count to 5, and after the user has entered 4 inputs, upon entering the last (5th) input I need to call a function.
