### ISSUE TITLE
Support for "fast paste SMS-code" on iOS, and "custom code paste" on Android

### ISSUE THREAD

**Issue by lapico** [retyui/react-native-confirmation-code-field#142]
Hi,

First of all, thanks for the clean and simple to use library.

We build an IOS / Android app with Expo (non-ejected) and the "fast paste" feature is not working on either of the targeted platforms.

There is no example in the documentation, do you have any insight on how to achieve this ?

Do we have to use the sms-retriever-api or missed something ?

Best regards

**Comment by retyui** [comment]
@lapico 

> fast paste

is an iOS system feature:

https://support.apple.com/guide/iphone/automatically-fill-in-sms-passcodes-on-iphone-iphc89a3a3af/ios

**Comment by lapico** [comment]
@retyui thanks for the quick answer,

What about "custom code paste" on Android, we tried the implementation from the examples but it didn't work.

Should we use `canPasteCode` or something like [this](https://github.com/retyui/react-native-confirmation-code-field/pull/36#issuecomment-462644571):
```
pasteCode(){
      if(this.field.current){
        const value = '123';
        field.current.handlerOnTextChange(value);
      }
  }
```

Any suggestion on what is the actual way to implement automatic copy/paste from sms ?

Thanks !

**Comment by retyui** [comment]
@lapico 

> What about "custom code paste" on Android
> Should we use canPasteCode or something like this:

Actually NO! this a legacy example. Since 5.x.x  `CodeField` is a stateless component and you should manipulate by your state value on the one layer above



```diff
// example for react-native-sms-retriever

import SmsRetriever from 'react-native-sms-retriever';


const App = () => {
  const [value, setValue] = useState('');

+  useEffect(() => {
+    const unsubscribe = () => SmsRetriever.removeSmsListener();

+    SmsRetriever.startSmsRetriever()
+      .then((registered) => {
+        if (registered) {
+          SmsRetriever.addSmsListener((event) => {
+            const code = getCodeBySmsMessage(event?.message);

+            if (code) {
+              // Call setValue to set SMS code
+              setValue(code);
+              unsubscribe();
+            }
+          });
+        }
+      })
+      .catch((error) => {
+        // trackException(error);
+      });

+    return unsubscribe;
+  }, []);

  return (
    <CodeField
      value={value}
      onChangeText={setValue}
      // ...
    />
  );
};

```

**Comment by lapico** [comment]
In my humble late experience, libraries like `react-native-sms-retriever` and `react-native-otp-verify` need native code and are not installing properly if Expo is not ejected.

I've found a workaround for Android using the Clipboard api:

```
import {Platform, Clipboard} from 'react-native';

...

useEffect(() => {
      if (Platform.OS !== 'android') return;
      const writeClipboard = async () => {
        await Clipboard.setString('');
      };
      const readClipboard = async () => {
        const clipboard = await Clipboard.getString();
        const regexp = new RegExp(`^\\d{${6}}$`);
        if (regexp.test(clipboard)) {
          setOtp(clipboard);
          clearInterval(interval);
        }
      };
      // reset clipboard
      writeClipboard();
      const interval = setInterval(() => {
        // check clipboard every second
        readClipboard();
      }, 1000);
      return () => clearInterval(interval);
    }, [])

...

```

And of course, sms needs to be formatted for the "copy" button to show :

`<#> Your app code is: 888888`

I still need to test that in production though.

**Comment by retyui** [comment]
@lapico Can I close issue?

**Comment by lapico** [comment]
Yes thanks again!
