### ISSUE TITLE
TypeError: setValue is not a function (clearByFocusCell)

### ISSUE THREAD

**Issue by firstfloordigital** [retyui/react-native-confirmation-code-field#143]
The app show TypeError: setValue is not a function and crashes.

react-native "0.61.5",
react-native-confirmation-code-field:6.5.0 (also tried 5.1.0 )

![Screenshot_5](https://user-images.githubusercontent.com/52122775/86945137-4d8afa00-c166-11ea-9e15-6f97e18a4eb2.png)

**Comment by retyui** [comment]
Please show how do you use this component?

**Comment by firstfloordigital** [comment]
const ref = useBlurOnFulfill({otpInput, cellCount: CELL_COUNT});
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    otpInput,
    setOtpInput,
  });

<CodeInputContainer>
              <CodeField
                ref={ref}
                {...props}
                value={otpInput}
                onChangeText={setOtpInput}
                cellCount={CELL_COUNT}
                keyboardType="number-pad"
                textContentType="oneTimeCode"
                rootStyle={styles.codeFieldRoot}
                renderCell={({index, symbol, isFocused}) => (
                  <View
                    // Make sure that you pass onLayout={getCellOnLayoutHandler(index)} prop to root component of "Cell"
                    onLayout={getCellOnLayoutHandler(index)}
                    key={index}
                    style={[styles.cellRoot, isFocused && styles.focusCell]}>
                    <Text style={styles.cellText}>
                      {symbol || (isFocused ? <Cursor /> : null)}
                    </Text>
                  </View>
                )}
              />
            </CodeInputContainer>

**Comment by retyui** [comment]
That easy to fix :

```js
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    value: otpInput,
    setValue: setOtpInput,
  });
```

**Comment by firstfloordigital** [comment]
Thanks a ton, @retyui , it solved the issue

**Comment by dannypaz** [comment]
@retyui do you know when the change to add `value` and `setValue` was made. I tried to check changelog

**Comment by retyui** [comment]
@dannypaz 

`useBlurOnFulfill` was added in [5.x.x](https://npmfs.com/compare/react-native-confirmation-code-field/4.0.0/5.0.1/) and has not changed since then

![image](https://user-images.githubusercontent.com/4661784/104806711-321e3d00-57e2-11eb-95b0-50277980aa81.png)
