### ISSUE TITLE
Keyboard not show after hide keyboard on Android

### ISSUE THREAD

**Issue by llleyelll** [retyui/react-native-confirmation-code-field#144]
If I hide keyboard on Android and tap code field to type again the keyboard won't show up. This issue is happens only on Android.

my code:
```typescript
<CodeField
    ref={ref}
    {...props}
    value={code}
    onChangeText={(code) => {
        setPinCode(code);
    }}
    cellCount={6}
    autoFocus={true}
    keyboardType={TextInputNumberPadType}
    renderCell={({ index, symbol, isFocused }) => (
        <View 
            style={styles.textInputPinCodeSingleDigit}
            key={index}
            onLayout={getCellOnLayoutHandler(index)}
        >
            <Text style={styles.pinInput}>
                {symbol || (<Text style={styles.singleOtpPlaceholder}>{!isFocused ? '__' : <Cursor/>}</Text>)}
            </Text>
        </View>
    )}
/>
```

**Comment by retyui** [comment]
@llleyelll 

Try to remove focus instead of hiding keyboard

**Comment by llleyelll** [comment]
I mean when I tap hide keyboard on device (Android). The keyboard won't show up.

**Comment by retyui** [comment]
@llleyelll 

I've just tried to reproduce this bug and I couldn't do that

Could you please record a video or create a demo repo?

**Comment by llleyelll** [comment]
My issue was solved by adding listener.
```
Keyboard.addListener('keyboardDidHide', keyboardHandler);
```
then using `blur()` to remove focus when keyboard dismissed.

You can close this issue. Thanks
