### ISSUE TITLE
Are the 'CodeField' props being exported?

### ISSUE THREAD

**Issue by sclavijo93** [retyui/react-native-confirmation-code-field#145]
I'm using typescript and I need to create a component named 'PinInput' that contains the CodeField component inside and I want all the props I pass to the 'PinInput' component to be redirected to the CodeField component. So when I create my 'PinInput' component's interface I put a CodeFieldProps type.

```
interface PinInputProps {
  CodeFieldProps?: ...;
}

const PinInput = ({CodeFieldProps} : PinInputProps) => {
  return <CodeField {...CodeFieldProps} />
}
```

and then use it like this
```
<PinInput value={pin} onChangeText={setPin} />
```

without typescript warnings.

Can anyone help me please? 🙏

**Comment by retyui** [comment]
```js

import { CodeField } from 'react-native-confirmation-code-field';

type PinInputProps = ComponentProps<typeof CodeField>;

```

**Comment by sclavijo93** [comment]
Great, I'm new in typescript so I didn't think in that approach. Thank you @retyui
