### ISSUE TITLE
Forward ref and useBlurOnFulfill

### ISSUE THREAD

**Issue by sclavijo93** [retyui/react-native-confirmation-code-field#146]
Hi, I need some help 😅  is there a way to use React forwardref and useBlurOnFulfill ath the same time? I have a custom component that has the CodeField component inside and I want to focus the CodeField programatically when onSubmitEditing of another textinput is triggered.

**Comment by retyui** [comment]
It help?
```js
const MyCodeField = React.forwardRef((props, forwardedRef) => {
  const ref = useBlurOnFulfill({ value, cellCount: CELL_COUNT });

  const { current: textInput } = ref;

  React.useImperativeHandle(forwardedRef, () => textInput, [textInput]);

  return <CodeField 
                ref={ref}
                //...
            />;
});
```

**Comment by sclavijo93** [comment]
Works like a charm! Thanks for the quick response!

**Comment by sclavijo93** [comment]
Thank you so much

**Comment by huduarte** [comment]
same happening here, any code example to follow?

**Comment by retyui** [comment]
@huduarte Did it help you https://github.com/retyui/react-native-confirmation-code-field/issues/146#issuecomment-672221576 is it?
