### ISSUE TITLE
how can i get value(verify code) on other Component?

### ISSUE THREAD

**Issue by stylewith** [retyui/react-native-confirmation-code-field#147]
hello! I am beginner development, student
I use UnderlineCode and I want to get value... help me plz

I have one Screen.js 
..
View
  UnderlineCode/
/View
..

I have this component UnderlineCode.js

If I run console.log (value) in UnderlineCode.js now, the value comes out.
However, I would like to store the value of UnderlineCode in State={code:''} in Screen.js. Ask if there's any way.

**Comment by retyui** [comment]
I hope the next example should help

https://github.com/retyui/react-native-confirmation-code-field/issues/122#issuecomment-620479087

**Comment by stylewith** [comment]
> I hope the next example should help
> 
> [#122 (comment)](https://github.com/retyui/react-native-confirmation-code-field/issues/122#issuecomment-620479087)

hello retyui~
thank you answer~
But I have some error T.T
I follow your answer But.... Can't find variable: value
where can i write value?? error is located at in Screen.js

**Comment by stylewith** [comment]
> I hope the next example should help
> 
> [#122 (comment)](https://github.com/retyui/react-native-confirmation-code-field/issues/122#issuecomment-620479087)

Oh!! I Change value={this.state.value}
Thankyou so much!! I love you ahahah

**Comment by retyui** [comment]
Your welcome
