### ISSUE TITLE
expo sdk 38 not compatible - Error "Object is not a constructor" on TextInput 

### ISSUE THREAD

**Issue by liorokach** [retyui/react-native-confirmation-code-field#148]
### Summary of Issue 
After upgrading 37.0.0 to sdk 38.0.0.
expo start resolved in success but when i try to open my application on simulator\phone i get an error.
on vscode terminal i get this message: "Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information".
on the simulator the error is "Object is not a constructor".
After debugging the issue i found out that the error came from this package - **please be aware and tell me if you solved it.**
After removing the use of the package my app start successfully.

![WhatsApp Image 2020-08-16 at 14 46 39](https://user-images.githubusercontent.com/24354248/90333549-76a57280-dfcf-11ea-8f1c-5c00ee25759c.jpeg)

### Environment 

Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.3.1 => 4.4.0

**Comment by retyui** [comment]
@liorokach 
Hi
It was fixed in the latest version!

**Comment by liorokach** [comment]
Thanks, i upgrade to 6.5 and now its working fine - closing the issue!
