### ISSUE TITLE
How to auto-fill for ios 12 >

### ISSUE THREAD

**Issue by anniewey** [retyui/react-native-confirmation-code-field#15]
I think this case only applicable to ios12 and above.

Steps to reproduce:
1. Receive confirmation code sms, it will show up above keypad automatically.
2. When tap on it, it will fill in to first text box only

Suspecting it was due to confirmation code is combined from single text boxes. Any idea how to support this?

**Comment by retyui** [comment]
The next version support to paste text
```
npm install react-native-confirmation-code-field@beta
```

[CHANGELOG](https://github.com/retyui/react-native-confirmation-code-field/blob/beta/CHANGELOG.md)

**Comment by anniewey** [comment]
Thanks, I'll try it out

**Comment by anniewey** [comment]
@retyui Hi, pasting props is working in beta version but how do I change the input color? I was unable to change the text color using `getInputStyle`
