### ISSUE TITLE
Add prop to disable the field and then pass that prop as well to renderCell

### ISSUE THREAD

**Issue by aprilmintacpineda** [retyui/react-native-confirmation-code-field#152]
The disabled prop will disable the text field so that when the form is submitting, the user should not be able to tap on the field.

```js
<CodeField
  disabled={isFormSubmitting}
  {...restOfProps}
/>
```

**Comment by retyui** [comment]
@aprilmintacpineda please try: 

```js
<CodeField
  editable={false}
  // ...
/>

```

**Comment by bryanltobing** [comment]
not sure why `editable` isn't in typescript prop types
