### ISSUE TITLE
can't click on first cell [iOS only]

### ISSUE THREAD

**Issue by krzysztofnowak** [retyui/react-native-confirmation-code-field#153]
I found issue with current implementation. It appears on ios devices only. Hardware, cause on simulators can't reproduce it

Scenario:
1. Fill all or several cells
2. Click on second cell - it gets focus, clears itself and all the following cells too
3. Click on first cell - instead of getting focus, a longpress tooltip appears

![Screenshot 2020-10-13 at 14 45 37](https://user-images.githubusercontent.com/7247704/95862604-71606c00-0d63-11eb-9b37-aab6e441662a.png)

**Comment by megantaylor** [comment]
i'm seeing this as well, only on iOS

**Comment by megantaylor** [comment]
if i click quickly multiple times (like 3-4?), it gets focus and clears

**Comment by megantaylor** [comment]
in testing, i was able to make click to clear on first cell work by passing a negative marginLeft equal to the width of a cell to `textInputStyle` and modifying the `findIndex` function in `useClearByFocusCell` to subtract the width of a cell from locationX before doing comparisons. but i really, really, really don't want to use this hack in production.

**Comment by sprotymo** [comment]
`textInputStyle={{
        justifyContent: "center",
        alignItems: "center",
      }}`

I settled on this solution, I think it's better than negative margins, but not good enough for production

**Comment by retyui** [comment]
@sprotymo Thanks 
I will revert it

**Comment by retyui** [comment]
Fixed in [6.5.1](https://npmfs.com/compare/react-native-confirmation-code-field/6.5.0/6.5.1/)
Thanks @sprotymo

**Comment by megantaylor** [comment]
in 6.5.1 now i cant clear cell on focus for any cell

**Comment by rjuevesano** [comment]
I'm trying to copy the code from email and paste it but there's no way to paste it. Does it support copy and paste? Right now, it only works with paste code from SMS.

**Comment by retyui** [comment]
@rjuevesano 
iOS or Android ?

**Comment by rjuevesano** [comment]
> @rjuevesano
> iOS or Android ?

I only tried on iOS

**Comment by ajlamarc** [comment]
Is there a solution to this issue yet for IOS?  I tried adding contextMenuHidden to the CodeField, which removes the popup but it still won't accept a click on the first box unless you tap on it 4 times back to back.

I tried adding @sprotymo 's style directly to the CodeField but that does not fix it, i may have to try @megantaylor 's solution if not.  I would prefer if copy and paste were not an option at all in my use case.

**Comment by retyui** [comment]
To fix this problem there is no silver bullet solution, but you can try: 

1) Workaround with `selection={{start,end}}` prop

I this case it prevents users to select the text (by double tap on text input), but it affects the appearing `copy/paste` menu
 
```js
      <CodeField
        selection={{
           start: value.length,
           end: value.length,
        }}
        // ...
     />
```

2) Workaround with `caretHidden={false/true}` prop


for this case, it works differently for cases when `value` empty or not for cases when user `tap` or `log tap` on empty\not empty cell


`caretHidden=true` - context menu doesn't appear : https://github.com/retyui/react-native-confirmation-code-field/issues/140
`caretHidden=false` - can't click on first cell https://github.com/retyui/react-native-confirmation-code-field/issues/153
