### ISSUE TITLE
more than one character in a cell

### ISSUE THREAD

**Issue by ignaciolopez12** [retyui/react-native-confirmation-code-field#155]
I need to generate 3 cells, and that in a cell more than one character can be allowed .. how can I do it with this library?

**Comment by retyui** [comment]
Could you please show a design that do you implement

**Comment by ignaciolopez12** [comment]
> Could you please show a design that do you implement

_____ - _______ - ____

2 characters would be placed in the first input, 5 characters in the second, and a character in the last

**Comment by retyui** [comment]
https://github.com/retyui/react-native-confirmation-code-field/tree/master/examples/DemoCodeField/src/FormattingExample

Just look at example
