### ISSUE TITLE
when i change onChangeText= value then the code input stops working

### ISSUE THREAD

**Issue by space-mvc** [retyui/react-native-confirmation-code-field#160]
I am trying to obtain the value of the code input.
When i use this below the code input works fine yet i cannot get the value

`onChangeText={setValue}`

when i change the code as below 

` onChangeText={(value) => console.log(value, 'test')}`

i get the console logs working correctly but the code input stops working on the screen. So all four spaces remain blank.

I also tried `setState()` instead of `console.log()` and this does not work either.
in general if i change the `onChangeText=` value then the code input stops working.

Does anybody know how to fix this?

**Comment by retyui** [comment]
If I understand correctly, it should fix your problem
```js
onChangeText={value => {
  setValue(value);
  myAnotherFunction(value);
}}


```

**Comment by space-mvc** [comment]
Hi when i use the following code the code input continues to work as normal

`onChangeText={value => {
     setValue(value);
 }}`

However how do i collect the value inside an onPress button action?

`onPress={() => {
     console.log({setValue});
 }}>Verify</Text>`

This just returns the following inside `console.log()` instead of a value

`{"setValue": [Function bound dispatchAction]}`

**Comment by space-mvc** [comment]
Here is the complete code, i started off from your animated example

`
import {Animated, Image, SafeAreaView, Text, View} from 'react-native';
import React, {useState} from 'react';

import {
  CodeField,
  Cursor,
  useBlurOnFulfill,
  useClearByFocusCell,
} from 'react-native-confirmation-code-field';

import styles, {
  ACTIVE_CELL_BG_COLOR,
  CELL_BORDER_RADIUS,
  CELL_SIZE,
  DEFAULT_CELL_BG_COLOR,
  NOT_EMPTY_CELL_BG_COLOR,
} from './styles';



const {Value, Text: AnimatedText} = Animated;

const CELL_COUNT = 4;
const source = {
  uri:
    'https://user-images.githubusercontent.com/4661784/56352614-4631a680-61d8-11e9-880d-86ecb053413d.png',
};

const animationsColor = [...new Array(CELL_COUNT)].map(() => new Value(0));
const animationsScale = [...new Array(CELL_COUNT)].map(() => new Value(1));
const animateCell = ({hasValue, index, isFocused}) => {
  Animated.parallel([
    Animated.timing(animationsColor[index], {
      useNativeDriver: false,
      toValue: isFocused ? 1 : 0,
      duration: 250,
    }),
    Animated.spring(animationsScale[index], {
      useNativeDriver: false,
      toValue: hasValue ? 0 : 1,
      duration: hasValue ? 300 : 250,
    }),
  ]).start();
};

const AnimatedExample = (props) => {
  let outputValue = '';
  const [value, setValue] = useState('');
  const ref = useBlurOnFulfill({value, cellCount: CELL_COUNT});
  const [props2, getCellOnLayoutHandler] = useClearByFocusCell({
    value,
    setValue,
  });

  const renderCell = ({index, symbol, isFocused}) => {
    const hasValue = Boolean(symbol);
    const animatedCellStyle = {
      backgroundColor: hasValue
        ? animationsScale[index].interpolate({
            inputRange: [0, 1],
            outputRange: [NOT_EMPTY_CELL_BG_COLOR, ACTIVE_CELL_BG_COLOR],
          })
        : animationsColor[index].interpolate({
            inputRange: [0, 1],
            outputRange: [DEFAULT_CELL_BG_COLOR, ACTIVE_CELL_BG_COLOR],
          }),
      borderRadius: animationsScale[index].interpolate({
        inputRange: [0, 1],
        outputRange: [CELL_SIZE, CELL_BORDER_RADIUS],
      }),
      transform: [
        {
          scale: animationsScale[index].interpolate({
            inputRange: [0, 1],
            outputRange: [0.2, 1],
          }),
        },
      ],
    };

    // Run animation on next event loop tik
    // Because we need first return new style prop and then animate this value
    setTimeout(() => {
      animateCell({hasValue, index, isFocused});
    }, 0);

    return (
      <AnimatedText
        key={index}
        style={[styles.cell, animatedCellStyle]}
        onLayout={getCellOnLayoutHandler(index)}>
        {symbol || (isFocused ? <Cursor /> : null)}
      </AnimatedText>
    );
  };

  return (
    <SafeAreaView style={styles.root}>
      <Text style={styles.title}>Verification</Text>
      <Image style={styles.icon} source={source} />
      <Text style={styles.subTitle}>
        Please enter the verification code{'\n'}
        we send to your mobile via sms
      </Text>

      <CodeField
        ref={ref}
        {...props}
        value={value}
        onChangeText={value => { setValue(value); }}
        cellCount={CELL_COUNT}
        rootStyle={styles.codeFieldRoot}
        keyboardType="number-pad"
        textContentType="oneTimeCode"
        renderCell={renderCell}

      />
      <View style={styles.nextButton}>
        <Text style={styles.nextButtonText}
        onPress={() => { console.log({setValue}); }}}>Verify</Text>
      </View>
    </SafeAreaView>
  );
};

export default AnimatedExample;
`

**Comment by retyui** [comment]
```js

onPress={() => { 
  setValue(currentValue => {
   console.log({currentValue});

   return currentValue;
  })
 }}>Verify</Text>



```

**Comment by retyui** [comment]
@space-mvc Can I close this issue ?
