### ISSUE TITLE
autofocus / ref.current.focus - Immediately loses focus / blur event after focus

### ISSUE THREAD

**Issue by AndreasA** [retyui/react-native-confirmation-code-field#161]
If I use autofocus or as a workaround ref.current.focus then the element is focused shortly but it immediately looses focus again. After adding a `onBlur` listener, it turns out that immediately a `onBlur` event is triggered.

This result in the keyboard opening and closing. If I do `ref.current.focus` with e.g. 500ms timeout it works but not sure if that  timeout is enough for all devices.

**Comment by AndreasA** [comment]
OK. I found out the issue it is not your fault the problem was that we navigate to the screen from a BottomSheet modal via react navigation and apparently the closing of the modal ensures the input loses focus. Tested by doing the navigation outside a modal where it works fine.

**Comment by alexfov** [comment]
@AndreasA you saved my time, thank you a lot for the explanation!
