### ISSUE TITLE
React Native Web - Error with new TextInput({})

### ISSUE THREAD

**Issue by davidbiller** [retyui/react-native-confirmation-code-field#162]
TypeError: react_native_web_dist_exports_TextInput__WEBPACK_IMPORTED_MODULE_6__.default is not a constructo

```
if (!new TextInput({})._onPress) {
     console.warn('[react-native-confirmation-code-field]: This version React Native not support hack for TextInput!');
 }
```

**Comment by retyui** [comment]
@davidbiller Please use the latest version of react-native-confirmation-code-field

**Comment by retyui** [comment]
Dublicated: https://github.com/retyui/react-native-confirmation-code-field/issues/148
