### ISSUE TITLE
Remove input on press not working

### ISSUE THREAD

**Issue by ertomz** [retyui/react-native-confirmation-code-field#163]
Hello! Thank you for this repository – insanely helpful!

This issue revolves around removing inputs. In the examples, when a user presses on a cell that already has an input in it, the rest of the cells ahead of it clear and the user can start typing again from where they pressed.

I copied all the code from here, but this doesn't seem to be working. 

If I'm understanding it correctly, this should be handled by using useClearByFocusCell?

Any help would be much appreciated! Thanks!

**Comment by retyui** [comment]
Do you use expo, or what rn version? 


Also, please try to run :

```sh
node node_modules/react-native-confirmation-code-field/path-rn-62.js
```

**Comment by ertomz** [comment]
Yes, using expo "~39.0.2". Installing that worked!!! Thanks so much :)
