### ISSUE TITLE
Is it possible to go back to the first index without deleting everything else?

### ISSUE THREAD

**Issue by maoryadin** [retyui/react-native-confirmation-code-field#169]
Is it possible to go back to the first index without deleting everything else?

**Comment by retyui** [comment]
Hi @maoryadin 

This behavior is not supported if you have an idea of how to implement it

 PR welcome

**Comment by maoryadin** [comment]
Thanks, i will implement

**Comment by sandesh1352** [comment]
Any update on this ?
