### ISSUE TITLE
Border radius not showing in ios devices.

### ISSUE THREAD

**Issue by gulsher7** [retyui/react-native-confirmation-code-field#172]
Hey react developers, if you facing border radius issue in ios devices. I have found one solution simply you just give overflow: 'hidden' props in your custom cell object style.

 cell: {
    width: 55,
    height: 55,
    lineHeight: 55,
    fontSize: 30,
    fontWeight: '700',
    textAlign: 'center',
    marginLeft: 16,
    backgroundColor: '#eee',
    borderRadius: 8,
    overflow: 'hidden' ---->>>>>>> add this props 
  },

**Comment by retyui** [comment]
React Native have issue with [border styles for `<Text/>` on iOS](https://github.com/facebook/react-native/issues/23537).

To fix it need `<View/>` wrapper for Cell, but don't forger to move `onLayout={getCellOnLayoutHandler(index)` to `<View/>`:

```js
// BAD 👎
renderCell={({index, symbol, isFocused}) => (
  <View key={index}>
    <Text
      onLayout={getCellOnLayoutHandler(index)}
    >
      {...}
    </Text>
  </View>
)}


// GOOD ✔️
renderCell={({index, symbol, isFocused}) => (
  <View
    key={index}
    onLayout={getCellOnLayoutHandler(index)}
  >
    <Text>{...}</Text>
  </View>
)}
```

**Comment by faerylay** [comment]
Thank you bro u save it @gulsher7

**Comment by rsfnarola** [comment]
Thanks alot !!

**Comment by huynhr** [comment]
Omg bless @retyui 🙏🏼
