### ISSUE TITLE
this package available on npm

### ISSUE THREAD

**Issue by ganesh-papola** [retyui/react-native-confirmation-code-field#173]
is this forked version available on npm or have to install from github?

**Comment by retyui** [comment]
Yes it available on npm with a new name https://www.npmjs.com/package/react-native-confirmation-code-field

```diff
+react-native-confirmation-code-field@6.5.1
-react-native-confirmation-code-input@1.0.4
```

**Comment by saaspeter** [comment]
hi @retyui , I am new to node.js, my project use npm package manager, and I don't want to switch to yarn, so Can I use npm install command to install it? like: npm install react-native-confirmation-code-field ? 
Thank you!
