### ISSUE TITLE
Ipad Design Support?

### ISSUE THREAD

**Issue by ganesh-papola** [retyui/react-native-confirmation-code-field#177]
Is this library supports Ipad or Tab designs?
<img width="548" alt="Screenshot 2021-05-05 at 5 57 15 PM" src="https://user-images.githubusercontent.com/19851598/117140704-5589e980-adcb-11eb-9c3d-363f2b610472.png">

Space btw two boxes is much. Any help with that?

**Comment by retyui** [comment]
Hi @ganesh-papola, For this case, you can limit the wrapper component width to reduce space

```tsx

const root = { maxWidth: (CELL_WIDTH + SPACE_BETWEEN) * CELL_COUNT }

  <CodeField
    rootStyle={root}
    // ...
  />
```

Docs: [CodeField::rootStyle](https://github.com/retyui/react-native-confirmation-code-field/blob/master/API.md#rootstyle-styleproprootcomponent)

**Comment by ganesh-papola** [comment]
Thanks It worked @retyui

**Comment by ganesh-papola** [comment]
Any solution for default box position to center for ipads ?
<img width="997" alt="Screenshot 2021-05-06 at 12 28 25 PM" src="https://user-images.githubusercontent.com/19851598/117254848-8ff49480-ae66-11eb-9600-cb00c03066dd.png">
<img width="1007" alt="Screenshot 2021-05-06 at 12 28 53 PM" src="https://user-images.githubusercontent.com/19851598/117254917-abf83600-ae66-11eb-8ac3-a0974b2a9c08.png">

**Comment by retyui** [comment]
A strongly recommend you read this article: https://reactnative.dev/docs/flexbox


you can try 2 variants: 

```tsx
root:{   // 1
  marginLeft: 'auto',
  marginRight: 'auto',
}

root:{   // or 2
  alignSeff: 'center'
}
```

**Comment by ganesh-papola** [comment]
@retyui I already tried it but the boxes were sticking together. I was asking if there was any prop for container style prop. I am managing with marginHorizontal now ..

**Comment by ganesh-papola** [comment]
Thanks for the comment btw
