### ISSUE TITLE
Option to paste

### ISSUE THREAD

**Issue by HyperNovax** [retyui/react-native-confirmation-code-field#178]
Hi,

It's possible to paste a code ? Stay press on the field and see the past option like a TextInput ?  
I try to do that on Android first !

Thank you !

**Comment by retyui** [comment]
By default caret is hidden:

https://github.com/retyui/react-native-confirmation-code-field/blob/f29e191489d12f5910e540fd18ccf65217840800/src/CodeField.tsx#L67-L69


You just change it (but be careful with issue: https://github.com/retyui/react-native-confirmation-code-field/issues/140)

```tsx
      <CodeField
        caretHidden={false}
     />
```

**Comment by HyperNovax** [comment]
Thank you @retyui for your answer ! It's work fine on Android. I will check the behavior on iOS.

**Comment by akinncar** [comment]
paste doesn't work on iOS for me

the box Copy/Paste is showing, but nothing happens

**Comment by retyui** [comment]
@akinncar could you please provide more information?

**Comment by akinncar** [comment]
yes, there is my code:

```js
export function RedeemCodeField ({ value, onChangeText, error, cellCount = 4, ...rest }) {
  return (
    <CodeField
      {...rest}
      value={value}
      onChangeText={onChangeText}
      cellCount={cellCount}
      keyboardType='number-pad'
      textContentType='oneTimeCode'
      caretHidden={false}
      renderCell={({ index, symbol, isFocused }) => (
        <PinField key={index} symbol={symbol} isFocused={isFocused} error={error} />
      )}
    />
  )
}
```

```js
handleChangeCode = code => {
  this.setState({ code, error: '' })
}

<RedeemCodeField
  autoFocus
  value={code}
  onChangeText={this.handleChangeCode}
  cellCount={6}
  error={error}
/>
```

**Comment by retyui** [comment]
@akinncar I created a expo snack  https://snack.expo.dev/DAcuvZz5x from your code

and it works for me

https://user-images.githubusercontent.com/4661784/150562000-5d3aa18b-bea1-4501-801e-14af5c41f1f9.mp4
