### ISSUE TITLE
useClearByFocusCell isnt working

### ISSUE THREAD

**Issue by megantaylor** [retyui/react-native-confirmation-code-field#180]
on version 7.1.0, expo 41 (i upgraded to the latest version of react-native-confirmation-code-field in the hopes that it would magically solve my problem, but it did not. problem also existed in 6.5.1)

i have a pretty basic CodeField implementation, and the useClearByFocusCell used to work so that if i clicked on a cell that was filled, it and all the cells after it would clear. now it doesn't work. 

it doesn't seem to be working in the demo, either: https://snack.expo.io/Zil!jCFft

as far as i can tell, the onPressOut function doesn't even get called when you click on a cell.

**Comment by retyui** [comment]
TextInput component does not include "onPressOut" functionally it means that SDK 41 does not use the latest 0.64.x React Native version:

https://github.com/expo/react-native/blob/sdk-41/Libraries/Components/TextInput/TextInput.js

And updating to 7.x.x version did not solve your issue

**Comment by megantaylor** [comment]
just trying to understand possible solutions, my options are either to revert to an old version of this library that uses the custom text input to add the on press event or write my own custom text input to add the on press event?

**Comment by retyui** [comment]
if you use expo@41 

 you have to use `yarn add react-native-confirmation-code-field@6`
