### ISSUE TITLE
Keybooard not dismissing automatically on input fullfill

### ISSUE THREAD

**Issue by vinaygoyal20** [retyui/react-native-confirmation-code-field#181]
React native version=>0.63.2
RTL mode is enabled.
"react-native-confirmation-code-field": "^6.7.0",

once the input is completed keyboard should be automatically dismissed but it's not closing automatically.

**Comment by retyui** [comment]
Please make sure that you use `useBlurOnFulfill` hook correctly

 

```tsx
const App = () => {
  const [value, setValue] = useState('');
  const ref = useBlurOnFulfill({value, cellCount: CELL_COUNT});

  return (
      <CodeField
        ref={ref}
        // ...
      />
  );
};
```

Just tested on the latest version  with RTL and it works

**Comment by GautierT** [comment]
Hi @retyui 
And how can I **not close** the keyboard on fulfill ? 

Thanks for this awesome lib !

**Comment by retyui** [comment]
@GautierT Don't use an `useBlurOnFulfill` hook and Keyboard won't close on fulfill

**Comment by GautierT** [comment]
As simple as that ! Thanks. 

The use of `useBlurOnFulfill` was not clear for me.

**Comment by retyui** [comment]
It is a very simple hook

When input value length equal cell count it just invoke `inputRef.blur()` method

https://github.com/retyui/react-native-confirmation-code-field/blob/0b3fa93ec2beadf115fd666f85fa7297f28cdaf2/src/useBlurOnFulfill.ts#L9-L22

**Comment by GautierT** [comment]
Okay got it.
It could be useful to be able to call an other function than bur. 
I want, for example, to go next page when value length equal cell count. Or trigger a form validation...

I did something like that : 
```
  useEffect(() => {
    console.log('value.length === CELL_COUNT: ', value.length === CELL_COUNT);
    if (value.length === CELL_COUNT) {
      onFull();
    }
  }, [value]);
```

onFull() is a function passed as a props that I want to call when input is "full".

Thanks for the explanation !
