### ISSUE TITLE
How to prevent next button getting focused after writing the code?

### ISSUE THREAD

**Issue by adrenaline681** [retyui/react-native-confirmation-code-field#187]
After I finish writing the 4 digits of the code, it will automatically create a gray box around the next TouchableOpacity component I have. How do I prevent this?

![Error](https://user-images.githubusercontent.com/12194431/139326890-e1cbe27d-9273-4458-bbc6-204fdb8e5807.JPG)

**Comment by retyui** [comment]
did it issue reproduced on Android and iOS ?

**Comment by adrenaline681** [comment]
I'm currently only working on Android, I have no way of texting in iOS

**Comment by retyui** [comment]
I react-native core behavior 

`useBlurOnFulfill` make blur when all code filled 

```tsx
textInputRef.blur() //  it will trigger highlighting the next touchable element
```

**Comment by retyui** [comment]
Try on a real device, seems this issue only reproduce on an android emulator
