### ISSUE TITLE
Render Cell element's color isn't applied in Dark Mode on Android

### ISSUE THREAD

**Issue by paulocf92** [retyui/react-native-confirmation-code-field#188]
I'm trying out this component on my Android (Xiaomi Mi 9T), but when I set the element color on renderCell prop to pure black '#000' and it is in Dark Mode (phone setting) it won't take effect, it just keeps white. It starts to apply the color from '#333' onwards. Since the cell background is an extra light grey color at all times (#F8F8F8) I have to keep it concise regardless if Dark Mode is on or not.

This is what I'm experiencing:
![darkmode](https://user-images.githubusercontent.com/6351070/140792640-2c1a7d0e-3432-4509-bd71-0b36c9119d80.jpg)

**Comment by retyui** [comment]
A black color gets inverted into White by your OS system, this module doesn't have any specific logic to prevent this behavior 

I found a question on StackOverflow for your case: https://stackoverflow.com/questions/57175226/how-to-disable-night-mode-in-my-application-even-if-night-mode-is-enable-in-andr

**Comment by paulocf92** [comment]
Kind thanks for this, I will adjust OS folder as pointed out.
