### ISSUE TITLE
Support clear function!

### ISSUE THREAD

**Issue by d3vma** [retyui/react-native-confirmation-code-field#189]
Hello, i am trying to get a clear function triggered but I can't see that anywhere in the documentation/examples! 

the plugin is quite helpful and I am actually using it for a production code, just need to get a `clear` method supported or it might be hidden somewhere!

**Comment by retyui** [comment]
@d3vma 

`CodeField` is a state-less component! So, when you need to clear state you have done it in your own state:

```tsx
import {useState} from 'react'

const App = ()=>{
  const [value,setValue] = useState('')

  const clear = ()=>setValue('')

  return <CodeField value={value} onChangeText={setValue} />
}

```

**Comment by d3vma** [comment]
@retyui My mistake I missed that! Cheers.
