### ISSUE TITLE
Can't autoFocus on first field

### ISSUE THREAD

**Issue by eduardosoller** [retyui/react-native-confirmation-code-field#191]
I cant make the autoFocus work. I didn't find this on the docs so can you provide an example?
Working with 
Expo SDK 42
React Native 0.63
react-native-confirmation-code-field@7.2

My code:

```tsx
<CodeField
        ref={ref}
        {...props}
        value={value}
        autoFocus={true}
        onChangeText={(val) => {
          setValue(val);
          onValueChange(val);
        }}
        cellCount={cellCount}
        rootStyle={styles.codeFieldRoot}
        keyboardType="number-pad"
        textContentType="oneTimeCode"
        renderCell={renderCell}
      />
      {error ? <Text style={styles.error}>{error}</Text> : null}
    </>

```

and import to in my component:

```tsx
<AuthCodeInput
                    {...props}
                    cellCount={6}
                    isPassword={true}
                    value={password}
                    onValueChange={(value) => setPassword(value)}
                    label="Digite a sua senha"
                />
```

Thank you so much for your time
Regards from Brazil

**Comment by retyui** [comment]
@eduardosoller Just passing a [`autoFocus`](autoFocus) prop is enough to focus text input

```tsx
<CodeField
        autoFocus={true}
```


https://user-images.githubusercontent.com/4661784/144316880-e9a93cbd-ce83-4493-8cc9-aac1bac7ca51.mp4

**Comment by eduardosoller** [comment]
Thanks for the answer
...but i can't get the autoFocus to work on my app.
I put your basic example as a separate view inside my project, downgraded your lib to version 6 and tested a TextInput with autoFocus prop and it worked but CodeField component didn't.
So still dont know whats happens...maybe some dependency issue?
Here is the main dependencies from my package.json:

    "react": "16.13.1",
    "react-dom": "16.13.1",
    "expo": "^42.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",

     Muito obrigado

**Comment by retyui** [comment]
@eduardosoller I see you use `react-navigation`,  try set autofocus only when the screen finish appearing animation!
