### ISSUE TITLE
Placeholder and it's styling

### ISSUE THREAD

**Issue by Prisoner-debugger** [retyui/react-native-confirmation-code-field#194]
Hi! I'm new at programming and I have a dumb question :
Do we have a way to create a placeholder if yes then how will it be styled?

**Comment by retyui** [comment]
placeholder?

could you please provide any images how it should looks like?

**Comment by Prisoner-debugger** [comment]
![OtpCodeField](https://user-images.githubusercontent.com/73497265/150560220-a8c94731-41c6-4562-871a-d30e2b9cf2d5.JPG)

**Comment by Prisoner-debugger** [comment]
this is as close I have gotten, I don't know how to change the color of X
![code](https://user-images.githubusercontent.com/73497265/150560725-826db078-d46e-49b5-8610-24c78b3cc0fc.JPG)


![appss](https://user-images.githubusercontent.com/73497265/150560384-da367d25-6b43-4de2-aeed-6258e49b1787.JPG)

**Comment by retyui** [comment]
![image](https://user-images.githubusercontent.com/4661784/150562763-a1dbf311-cfaf-406f-b241-c3fbb228a521.png)

```tsx
style={[styles.cell, isFocused && styles.focusCell, !symbol && {color: 'red'} ]}
                                                                        ^^^ if no symbol apply red color             
```

**Comment by Prisoner-debugger** [comment]
Thanks a lot it worked
