### ISSUE TITLE
Cell Style

### ISSUE THREAD

**Issue by enessahin1** [retyui/react-native-confirmation-code-field#195]
Hi! I have been giving borderRadius to cell style but it is not working as well and I gave borderWeigth and borderRadius then i saw that! What can i do for it. 
![image](https://user-images.githubusercontent.com/32218898/150671300-cad59513-7b8f-4359-832e-3b41e9cf3253.png)

**Comment by retyui** [comment]
@enessahin1 thy to use `<View/>` as root component of cell

it can be known issue please read: https://github.com/retyui/react-native-confirmation-code-field/tree/master/examples/DemoCodeField/src/UnderlineExample#underline-example
