### ISSUE TITLE
Hide keyboard by props

### ISSUE THREAD

**Issue by liho00** [retyui/react-native-confirmation-code-field#198]
Can I request a feature to hide the keyboard by default with prop?

**Comment by retyui** [comment]
I don't untested what you mean "hide the keyboard by default"

**Comment by retyui** [comment]
In this case have to disable pointer events to prevent any taps on input (it won't open keyboard)

-  https://reactnative.dev/docs/view#pointerevents

**Comment by liho00** [comment]
> In this case have to disable pointer events to prevent any taps on input (it won't open keyboard)
> 
> * https://reactnative.dev/docs/view#pointerevents

Yes, its working! Very Wise! @retyui
