### ISSUE TITLE
My app crash when I tap on the boxes

### ISSUE THREAD

**Issue by rgarcia-longevo** [retyui/react-native-confirmation-code-field#204]
Hi, Team. I found an issue in your component. I think it isn't a critical one but it's an issue.
<img width="504" alt="Screen Shot 2022-04-06 at 14 49 30" src="https://user-images.githubusercontent.com/102546968/162037515-37c726af-2bb9-4fb8-a68f-33132fe00e16.png">

When I tap fastly 10 or more times over the boxes, the app crash.
<img width="504" alt="Screen Shot 2022-04-06 at 14 50 31" src="https://user-images.githubusercontent.com/102546968/162037756-f435f9d3-2877-40bb-9364-18fffca9135b.png">

Sometimes, the app crash when the 3rd. or 4th. tap happens.

TESTING DETAILS:
 Device: iphone 8
 OS: iOS 14.4

**Comment by retyui** [comment]
can you reproduce it on debug build ?

**Comment by rgarcia-longevo** [comment]
Thank you @retyui I had a mistake in the way in which I'm using the component.
You can close this issue. Thank you very much!

**Comment by bekatd** [comment]
@rgarcia-longevo Can you clarify what mistake you made? I'm having the same problem right now on an iOS device, but not on an Android emulator.

**Comment by bekatd** [comment]
I have everything exactly like in the example
