### ISSUE TITLE
Entered data from right of the cursor is deleting when randomly removing the text from cell

### ISSUE THREAD

**Issue by chinmay4github1987** [retyui/react-native-confirmation-code-field#205]
If I remove 3rd cell, next cells text is removed automatically

**Comment by gani419** [comment]
This issue is happening for me also.
If the cell count is 6. If I place cursor in 3rd cell, then 4,5 and 6 are also getting deleted.

**Comment by retyui** [comment]
> If the cell count is 6. If I place cursor in 3rd cell, then 4,5 and 6 are also getting deleted.

That's right, it's core behavior (not an issue)

if you have ideas how to improve it PR welcome

**Comment by gani419** [comment]
Ok. Thank you for the response.

**Comment by jp0707** [comment]
> > If the cell count is 6. If I place cursor in 3rd cell, then 4,5 and 6 are also getting deleted.
> 
> That's right, it's core behavior (not an issue)
> 
> if you have ideas how to improve it PR welcome

@retyui The onChangeText is not called when clicking any cell, resulting in validations failing. I am using this to enter a 6-digit PIN. When I enter the correct PIN and then click on any previous cell and continue, the PIN validation passes and allows me to log in which it should not.
