### ISSUE TITLE
Prevent Keyboard from dismissing when all inputs filled

### ISSUE THREAD

**Issue by jgudo** [retyui/react-native-confirmation-code-field#206]
First of all, I just want to thank you for this amazing library! 

My question is, how do I prevent the keyboard from dismissing upon filling out all the fields? Is there a prop available for this?

**Comment by davydspotnana** [comment]
@jgudo `useBlurOnFulfill` do this logic, so just do not use it)

```
  const ref = useBlurOnFulfill({value, cellCount: CELL_COUNT});
```

**Comment by jgudo** [comment]
@davydspotnana Got it! Now  it's working as expected. Thank you!
