### ISSUE TITLE
Impossible use different variable name 

### ISSUE THREAD

**Issue by iim-norse** [retyui/react-native-confirmation-code-field#208]
TypeError: setValue is not a function. (In 'setValue(text)', 'setValue' is undefined)
<img width="623" alt="Знімок екрана 2022-06-11 о 15 12 43" src="https://user-images.githubusercontent.com/99746223/173187555-b698d8c7-6b80-4c21-a599-84b1ac1c8e2a.png">
when I use variables different from this: 
`const [ value, setValue ] = useState('');`
for example if you try `const [ value1, setValue1 ] = useState('');` get this error

**Comment by retyui** [comment]
I have an intelligent solution for you issue:

```tsx
const [ myValue1, setMyValue1 ] = useState('');

 const ref = useBlurOnFulfill({value:myValue1, cellCount: CELL_COUNT});
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    value: myValue1,
    setValue: setMyValue1,
  });

```
