### ISSUE TITLE
Input fields accepting ,- and all.

### ISSUE THREAD

**Issue by bgrgit** [retyui/react-native-confirmation-code-field#210]
![Screenshot_1656146963](https://user-images.githubusercontent.com/31758716/175765956-52a0df60-db7f-4a37-9a9c-0fe139bb4330.png)
Input field should not attend any input other than number. How to do that. Please help me

**Comment by retyui** [comment]
It is not an issue of this library

Solution: https://stackoverflow.com/questions/32946793/react-native-textinput-that-only-accepts-numeric-characters
