### ISSUE TITLE
App crashes when I tap on the boxes

### ISSUE THREAD

**Issue by bekatd** [retyui/react-native-confirmation-code-field#212]
https://user-images.githubusercontent.com/6948919/184475319-4804d916-f092-4236-a3a0-82307c13a9a1.mov

    import React, { useState } from 'react';
    import { Text, KeyboardAvoidingView, View, TouchableOpacity } from 'react-native';
    import { connect } from 'react-redux';
    import { SafeAreaView } from 'react-native-safe-area-context';
    import { vs, s, ScaledSheet } from 'react-native-size-matters';
    import {
       CodeField,
       Cursor,
       useBlurOnFulfill,
       useClearByFocusCell,
    } from 'react-native-confirmation-code-field';

    import BackComponent from 'core/Components/Icons/BackComponent';
    import CustomScaledButton from 'core/Components/BuildingBlocks/CustomScaledButton/CustomScaledButtonComponent';

    import { Colors } from 'core/Theme';
    import { isIOS } from 'App/Utils/Platform';
    import AuthActions from 'core/Stores/Auth/Actions';

    const CELL_COUNT = 6;

    const OTPScreen = ({ navigation, header, title, email, onSubmit, requestOTP, ...rest }) => {
       const [code, setCode] = useState('');
       const otpFieldRef = useBlurOnFulfill({ code, cellCount: CELL_COUNT });
       const [props, getCellOnLayoutHandler] = useClearByFocusCell({ code, setCode });

       const onPressSubmit = () => onSubmit({ type: 1, code, email, ...rest });

       code.length === CELL_COUNT && onPressSubmit();

       const _requestOTP = () => {
          requestOTP({ email });
       };

       return (
          <SafeAreaView style={styles.container}>
             <KeyboardAvoidingView style={styles.wrapper} behavior={isIOS ? 'padding' : 'height'}>
                <View>
                   <View style={styles.backButton}>
                      <BackComponent onPress={navigation.goBack} />
                      <Text style={styles.header}>{header}</Text>
                   </View>
                   <Text style={styles.title}>{title}</Text>
                   <CodeField
                      ref={otpFieldRef}
                      {...props}
                      value={code}
                      onChangeText={setCode}
                      cellCount={CELL_COUNT}
                      rootStyle={styles.mx20}
                      keyboardType='number-pad'
                      textContentType='oneTimeCode'
                      renderCell={({ index, symbol, isFocused }) => {
                         return (
                            <View
                               // Make sure that you pass onLayout={getCellOnLayoutHandler(index)} prop to root component of "Cell"
                               key={index}
                               onLayout={getCellOnLayoutHandler(index)}
                               style={[styles.cell, isFocused && styles.focusCell]}>
                               <Text style={styles.cellCursor}>
                                  {symbol || (isFocused ? <Cursor /> : null)}
                               </Text>
                            </View>
                         );
                      }}
                   />
                   <Text style={styles.hint}>
                      We just sent a verification code to your email. Please enter the code above.
                   </Text>
                </View>
                <View style={styles.w100}>
                   <TouchableOpacity style={styles.resendButton} onPress={_requestOTP}>
                      <Text style={styles.resendText}>Resend code</Text>
                   </TouchableOpacity>
                   <CustomScaledButton
                      title='Done'
                      style={styles.button}
                      disabled={code.length === 6 ? false : true}
                      active={true}
                      onPress={code.length === CELL_COUNT && onPressSubmit}
                   />
                </View>
             </KeyboardAvoidingView>
          </SafeAreaView>
       );
    };

    const styles = ScaledSheet.create({
       container: {
          flex: 1,
          backgroundColor: Colors.backgroundColor,
       },
       wrapper: {
          flex: 1,
          justifyContent: 'space-between',
       },
       header: {
          fontSize: 20,
       },
       title: {
          fontSize: '26@s',
          color: Colors.primary,
          marginVertical: vs(50),
          fontWeight: 'bold',
          alignSelf: 'center',
       },
       backButton: {
          flexDirection: 'row',
          alignItems: 'center',
          paddingVertical: 10,
          paddingHorizontal: 20,
       },
       cell: {
          width: s(50),
          height: s(50),
          borderWidth: 1.5,
          borderColor: Colors.extraLight,
          backgroundColor: Colors.inputBox,
          borderRadius: 5,
          alignItems: 'center',
          justifyContent: 'center',
       },
       focusCell: {
          borderColor: Colors.primary,
       },
       cellCursor: {
          color: Colors.primary,
          fontWeight: '700',
          fontSize: 20,
       },
       mx20: {
          marginHorizontal: 20,
       },
       w100: {
          width: '100%',
       },
       resendButton: {
          alignItems: 'center',
          marginVertical: 20,
       },
       resendText: {
          color: Colors.primary,
          fontWeight: 'bold',
          fontSize: 15,
       },
       button: {
          marginBottom: '20@vs',
          alignSelf: 'center',
          width: '90%',
          height: 50,
          borderRadius: 10,
       },
       hint: {
          margin: 20,
          color: Colors.extraLight,
          textAlign: 'center',
          fontSize: 14,
          fontWeight: '600',
          marginHorizontal: 50,
          maxWidth: s(300),
          alignSelf: 'center',
       },
    });

    const mapDispatchToProps = (dispatch) => ({
       requestOTP: (data) => dispatch(AuthActions.requestOTP(data)),
    });

    export default connect(null, mapDispatchToProps)(OTPScreen);

**Comment by retyui** [comment]
please provide more information or it will be closed

**Comment by bekatd** [comment]
I added code and video of crash

**Comment by retyui** [comment]
```diff
-const [props, getCellOnLayoutHandler] = useClearByFocusCell({ code, setCode });
+const [props, getCellOnLayoutHandler] = useClearByFocusCell({ value: code, setValue: setCode });
```

**Comment by bekatd** [comment]
omg thanks <3
