### ISSUE TITLE
Autofocus code field on screen render

### ISSUE THREAD

**Issue by andreweinhorn** [retyui/react-native-confirmation-code-field#215]
Is it possible to autofocus the code field when the screen first renders?  

<img width="579" alt="have vs want" src="https://user-images.githubusercontent.com/2414383/198516567-ee89b4d7-adc0-46e4-87a9-fc1eb647c690.png">

**Comment by retyui** [comment]
it should works:

```tsx
<CodeField
  autoFocus={true}
/>
```


if you are using an react-navigation you have to know about issues:
- https://github.com/react-navigation/react-navigation/issues/9875
- https://github.com/react-navigation/react-navigation/issues?q=is%3Aissue++autoFocus+
