### ISSUE TITLE
Missing InputComponent from CodeField prop types

### ISSUE THREAD

**Issue by danieldunderfelt** [retyui/react-native-confirmation-code-field#219]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-confirmation-code-field@7.3.1` for the project I'm working on.

The InputComponent was missing from the props of CodeField, this patch adds it.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-confirmation-code-field/esm/CodeField.d.ts b/node_modules/react-native-confirmation-code-field/esm/CodeField.d.ts
index d9259e0..e7369b2 100644
--- a/node_modules/react-native-confirmation-code-field/esm/CodeField.d.ts
+++ b/node_modules/react-native-confirmation-code-field/esm/CodeField.d.ts
@@ -27,6 +27,7 @@ interface BaseProps {
   renderCell: (options: RenderCellOptions) => ReactNode;
   RootProps?: ViewProps;
   RootComponent?: ComponentType<ViewProps>;
+  InputComponent?: ComponentType<TextInputProps>;
   rootStyle?: ViewProps['style'];
   textInputStyle?: StyleProp<TextStyle>;
   cellCount?: number;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by retyui** [comment]
Overload is handling `InputComponent` props 


```tsx
export interface CodeFieldOverridableComponent {
  <C extends ElementType>(
    props: {InputComponent: C} & OmitStyle<ComponentPropsWithRef<C>> &
      BaseProps,
  ): ReactElement;

  (props: Props): ReactElement;
}
```

can you explain the issue more?

**Comment by danieldunderfelt** [comment]
I tried to add the InputComponent prop. Typescript said it doesn't exist. I added it, now it works.

**Comment by retyui** [comment]
@danieldunderfelt could you create a demo of this issue?

**Comment by danieldunderfelt** [comment]
Can you not replicate it?

**Comment by danieldunderfelt** [comment]
Huh, today it seems to work without the patch. Some weird Typescript issue then.
