### ISSUE TITLE
can't paste on first cell when caretHidden [iPhone SE(2nd), Google Pixel]

### ISSUE THREAD

**Issue by elencho** [retyui/react-native-confirmation-code-field#220]
I am using CarretHidden but still can't paste on first cell on some devices,

https://user-images.githubusercontent.com/53994979/230579026-304a5c3f-6e3f-442b-98ac-1136660e1bc6.mov

usage: 

      <CodeField
        ref={ref}
        {...props}
        value={value}
        onChangeText={handleValue}
        caretHidden={false}
        cellCount={cellCount}
        keyboardType="number-pad"
        textContentType="oneTimeCode"
        renderCell={({ index, symbol, isFocused }) => (
          <AppText
            key={index}
            style={[styles.cell, isFocused && styles.focusCell]}
            onLayout={getCellOnLayoutHandler(index)}
            header
          >
            {symbol || (isFocused ? <Cursor /> : null)}
          </AppText>
        )}
      />
    </>

**Comment by davydspotnana** [comment]
```
<CodeField
  // if copy/paste menu does not appear use
  caretHidden={false}
/>;
```

**Comment by retyui** [comment]
`caretHidden={false}` should helps, Any ideas why it's happening ?

**Comment by elencho** [comment]
No, No idea :/

**Comment by ChangeSomeCode** [comment]
same thing on base examples - `react-native-confirmation-code-field@7.3.1`
