### ISSUE TITLE
Numbers aren't being inputted 

### ISSUE THREAD

**Issue by tarajima** [retyui/react-native-confirmation-code-field#227]
Device: Samsung Galaxy S20 FE 5G
AndroidOS ver. 13; OneUI 5.1

I'm entering the numbers in my keypad but they're not being inputted, although the focus changes from one cell to the next. Here's my code in relation to the code confirmation field:
 
```tsx
const CELL_COUNT = 6

export function PhoneVerification({ navigation, route }) {

// ...

  const ref = useBlurOnFulfill({ value, cellCount: CELL_COUNT })
  const [error, setError] = useState(null)
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    value,
    setValue,
  })

  const handleChangeValue = val => {
    error && setError(null)
    setValue(val)
  }


return (
// ...
         <CodeField
            ref={ref}
            {...props}
            value={value}
            onChangeText={handleChangeValue}
            cellCount={CELL_COUNT}
            rootStyle={styles.codeFieldRoot}
            keyboardType='number-pad'
            textContentType='oneTimeCode'
            renderCell={({ index, symbol, isFocused }) => (
              <Text
                maxFontSizeMultiplier={1.1}
                key={index}
                style={[
                  styles.cell,
                  isFocused && styles.focusCell,
                  error && styles.errorCell,
                ]}
                onLayout={getCellOnLayoutHandler(index)}>
                {symbol || (isFocused ? <Cursor /> : null)}
              </Text>
            )}
          />
// ... 
)

const styles = StyleSheet.create({
  codeFieldRoot: {
    marginTop: 40,
    marginBottom: 12,
    justifyContent: 'center',
  },
  cell: {
    width: 44,
    height: 50,
    fontSize: 16,
    borderWidth: 1,
    lineHeight: 46,
    borderColor,
    textAlign: 'center',
    fontFamily: mainFont,
    borderRadius,
    marginHorizontal: gutter / 3,
  },
  focusCell: {
    borderColor: focusColor,
  },
  errorCell: {
    borderColor: errorColor,
  },
})

```

https://github.com/retyui/react-native-confirmation-code-field/assets/32473861/276c93bc-bb8e-4a2b-bdc6-5899583a8ae4

**Comment by retyui** [comment]
I used you code example to reproduce issue : https://snack.expo.dev/@retyui/blissful-yellow-croissant

but it works, can you show me all code of PhoneVerification component

**Comment by retyui** [comment]
@tarajima ping...

**Comment by Abraham10x** [comment]
Hello please am also have the same issues.
the numbers are not displaying on the emulator and a lot of mobile devices
`const VerifyAccount = ({ navigation }) => {
  const theme = useTheme();
  const CELL_COUNT = 4;
  const styles = useStyleSheet(themedStyles);
  const [value, setValue] = React.useState('');
  const ref = useBlurOnFulfill({ value, cellCount: CELL_COUNT });
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    value,
    setValue,
  });

  return (
    <Container light padded={false}>
      <TopNavigation title="Forgot Password" pressBack />
      <Content>
        <View style={styles.instrucContainer}>
          <Text style={[styles.bodySmallText, styles.instructionText]}>
            Kindly enter the OTP code sent to your registered email address.
          </Text>

          <View style={styles.optContainer}>
            <CodeField
              ref={ref}
              {...props}
              // Use `caretHidden={false}` when users can't paste a text value, because context menu doesn't appear
              value={value}
              onChangeText={setValue}
              cellCount={CELL_COUNT}
              rootStyle={styles.codeFieldRoot}
              keyboardType="number-pad"
              textContentType="oneTimeCode"
              renderCell={({ index, symbol, isFocused }) => (
                <Text
                  key={index}
                  style={[styles.cell, isFocused && styles.focusCell]}
                  onLayout={getCellOnLayoutHandler(index)}>
                  {symbol || (isFocused ? <Cursor /> : null)}
                </Text>
              )}
            />
          </View>
          <View style={styles.terms}>
            <Text style={{ color: '#333333' }} category="subhead">
              Didn't get code?
              <Text
                style={{ color: '#E5AF0E', textDecorationLine: 'underline' }}
                category="subhead">
                {' '}
                Resend Code
              </Text>
            </Text>
          </View>
        </View>
        <View style={styles.btnContainer}>
          <Button
            onPress={() => {
              navigation.navigate(ROUTES.NEWPASSWORD);
            }}
            activeOpacity={0.9}
            style={{ borderRadius: s(5) }}
            size="large"
            disabled={false}>
            Continue
          </Button>
        </View>
      </Content>
    </Container>
  );
};

const themedStyles = StyleService.create({
  optContainer: {
    marginTop: s(50),
    flexDirection: 'row',
    gap: vs(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: ms(10),
    paddingTop: vs(20),
    paddingBottom: vs(10),
    marginBottom: vs(20),
    backgroundColor: '#FFFFFF',
    ...boxShadow(0, 10, 3.85, 'rgba(50, 55, 140, 0.5)', 0.08, 84),
  },
  instrucContainer: {
    marginTop: ms(22),
    marginHorizontal: s(16),
  },
  terms: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: s(16),
    textAlign: 'center',
  },
  instructionText: {
    color: '#333333',
  },
  bodySmallText: {
    fontFamily: 'Lora-Regular',
    color: '#333333',
    fontWeight: '400',
    fontSize: s(13),
    lineHeight: s(20),
  },
  btnContainer: {
    justifyContent: 'flex-end',
    marginHorizontal: s(60),
    marginBottom: '5%',
  },
  cardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  root: { flex: 1, padding: 20 },
  codeFieldRoot: { marginBottom: vs(10) },
  cell: {
    width: 50,
    height: 50,
    lineHeight: 38,
    fontSize: 24,
    borderColor: '#E1E6EF',
    textAlign: 'center',
    borderBottomWidth: 3,
    paddingHorizontal: s(10),
    marginHorizontal: s(10),
  },
  focusCell: {
    borderColor: '#000',
  },
});`

**Comment by Abraham10x** [comment]
`const VerifyAccount = ({ navigation }) => {
  const theme = useTheme();
  const CELL_COUNT = 4;
  const styles = useStyleSheet(themedStyles);
  const [value, setValue] = React.useState('');
  const ref = useBlurOnFulfill({ value, cellCount: CELL_COUNT });
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    value,
    setValue,
  });

  return (
    <Container light padded={false}>
      <TopNavigation title="Forgot Password" pressBack />
      <Content>
        <View style={styles.instrucContainer}>
          <Text style={[styles.bodySmallText, styles.instructionText]}>
            Kindly enter the OTP code sent to your registered email address.
          </Text>

          <View style={styles.optContainer}>
            <CodeField
              ref={ref}
              {...props}
              // Use `caretHidden={false}` when users can't paste a text value, because context menu doesn't appear
              value={value}
              onChangeText={setValue}
              cellCount={CELL_COUNT}
              rootStyle={styles.codeFieldRoot}
              keyboardType="number-pad"
              textContentType="oneTimeCode"
              renderCell={({ index, symbol, isFocused }) => (
                <Text
                  key={index}
                  style={[styles.cell, isFocused && styles.focusCell]}
                  onLayout={getCellOnLayoutHandler(index)}>
                  {symbol || (isFocused ? <Cursor /> : null)}
                </Text>
              )}
            />
          </View>
          <View style={styles.terms}>
            <Text style={{ color: '#333333' }} category="subhead">
              Didn't get code?
              <Text
                style={{ color: '#E5AF0E', textDecorationLine: 'underline' }}
                category="subhead">
                {' '}
                Resend Code
              </Text>
            </Text>
          </View>
        </View>
        <View style={styles.btnContainer}>
          <Button
            onPress={() => {
              navigation.navigate(ROUTES.NEWPASSWORD);
            }}
            activeOpacity={0.9}
            style={{ borderRadius: s(5) }}
            size="large"
            disabled={false}>
            Continue
          </Button>
        </View>
      </Content>
    </Container>
  );
};

const themedStyles = StyleService.create({
  optContainer: {
    marginTop: s(50),
    flexDirection: 'row',
    gap: vs(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: ms(10),
    paddingTop: vs(20),
    paddingBottom: vs(10),
    marginBottom: vs(20),
    backgroundColor: '#FFFFFF',
    ...boxShadow(0, 10, 3.85, 'rgba(50, 55, 140, 0.5)', 0.08, 84),
  },
  instrucContainer: {
    marginTop: ms(22),
    marginHorizontal: s(16),
  },
  terms: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: s(16),
    textAlign: 'center',
  },
  instructionText: {
    color: '#333333',
  },
  bodySmallText: {
    fontFamily: 'Lora-Regular',
    color: '#333333',
    fontWeight: '400',
    fontSize: s(13),
    lineHeight: s(20),
  },
  btnContainer: {
    justifyContent: 'flex-end',
    marginHorizontal: s(60),
    marginBottom: '5%',
  },
  cardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  root: { flex: 1, padding: 20 },
  codeFieldRoot: { marginBottom: vs(10) },
  cell: {
    width: 50,
    height: 50,
    lineHeight: 38,
    fontSize: 24,
    borderColor: '#E1E6EF',
    textAlign: 'center',
    borderBottomWidth: 3,
    paddingHorizontal: s(10),
    marginHorizontal: s(10),
  },
  focusCell: {
    borderColor: '#000',
  },
});``const VerifyAccount = ({ navigation }) => {
  const theme = useTheme();
  const CELL_COUNT = 4;
  const styles = useStyleSheet(themedStyles);
  const [value, setValue] = React.useState('');
  const ref = useBlurOnFulfill({ value, cellCount: CELL_COUNT });
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    value,
    setValue,
  });

  return (
    <Container light padded={false}>
      <TopNavigation title="Forgot Password" pressBack />
      <Content>
        <View style={styles.instrucContainer}>
          <Text style={[styles.bodySmallText, styles.instructionText]}>
            Kindly enter the OTP code sent to your registered email address.
          </Text>

          <View style={styles.optContainer}>
            <CodeField
              ref={ref}
              {...props}
              // Use `caretHidden={false}` when users can't paste a text value, because context menu doesn't appear
              value={value}
              onChangeText={setValue}
              cellCount={CELL_COUNT}
              rootStyle={styles.codeFieldRoot}
              keyboardType="number-pad"
              textContentType="oneTimeCode"
              renderCell={({ index, symbol, isFocused }) => (
                <Text
                  key={index}
                  style={[styles.cell, isFocused && styles.focusCell]}
                  onLayout={getCellOnLayoutHandler(index)}>
                  {symbol || (isFocused ? <Cursor /> : null)}
                </Text>
              )}
            />
          </View>
          <View style={styles.terms}>
            <Text style={{ color: '#333333' }} category="subhead">
              Didn't get code?
              <Text
                style={{ color: '#E5AF0E', textDecorationLine: 'underline' }}
                category="subhead">
                {' '}
                Resend Code
              </Text>
            </Text>
          </View>
        </View>
        <View style={styles.btnContainer}>
          <Button
            onPress={() => {
              navigation.navigate(ROUTES.NEWPASSWORD);
            }}
            activeOpacity={0.9}
            style={{ borderRadius: s(5) }}
            size="large"
            disabled={false}>
            Continue
          </Button>
        </View>
      </Content>
    </Container>
  );
};

const themedStyles = StyleService.create({
  optContainer: {
    marginTop: s(50),
    flexDirection: 'row',
    gap: vs(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: ms(10),
    paddingTop: vs(20),
    paddingBottom: vs(10),
    marginBottom: vs(20),
    backgroundColor: '#FFFFFF',
    ...boxShadow(0, 10, 3.85, 'rgba(50, 55, 140, 0.5)', 0.08, 84),
  },
  instrucContainer: {
    marginTop: ms(22),
    marginHorizontal: s(16),
  },
  terms: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: s(16),
    textAlign: 'center',
  },
  instructionText: {
    color: '#333333',
  },
  bodySmallText: {
    fontFamily: 'Lora-Regular',
    color: '#333333',
    fontWeight: '400',
    fontSize: s(13),
    lineHeight: s(20),
  },
  btnContainer: {
    justifyContent: 'flex-end',
    marginHorizontal: s(60),
    marginBottom: '5%',
  },
  cardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  root: { flex: 1, padding: 20 },
  codeFieldRoot: { marginBottom: vs(10) },
  cell: {
    width: 50,
    height: 50,
    lineHeight: 38,
    fontSize: 24,
    borderColor: '#E1E6EF',
    textAlign: 'center',
    borderBottomWidth: 3,
    paddingHorizontal: s(10),
    marginHorizontal: s(10),
  },
  focusCell: {
    borderColor: '#000',
  },
});`
