### ISSUE TITLE
onChangeText  Final output Trigger twice

### ISSUE THREAD

**Issue by jianxinzhoutiti** [retyui/react-native-confirmation-code-field#231]
![image](https://github.com/retyui/react-native-confirmation-code-field/assets/22340846/7569317c-83fe-4148-b86f-044825445df4)
![image](https://github.com/retyui/react-native-confirmation-code-field/assets/22340846/21d14344-5046-4120-8fbd-77433002dd09)
![image](https://github.com/retyui/react-native-confirmation-code-field/assets/22340846/685bf63e-92cf-4748-9f66-b02148ff141f)

**Comment by retyui** [comment]
what version of react-native did you use ?

**Comment by jianxinzhoutiti** [comment]
@retyui  "react": "18.2.0",    "react-native": "0.72.3",

**Comment by retyui** [comment]
I tested it on `"react": "18.2.0", "react-native": "0.72.3",` 
using an example from `README` file and it works properly


<img width="1004" alt="Screenshot 2023-11-14 at 12 00 03" src="https://github.com/retyui/react-native-confirmation-code-field/assets/4661784/b4233f15-96fa-4f72-a695-a9cff376477f">

**Comment by jianxinzhoutiti** [comment]
Thank you. It's probably the simulator，I have no problem with my phone @retyui Thank you very much
