### ISSUE TITLE
Unable to paste on mobile

### ISSUE THREAD

**Issue by oliviercperrier** [retyui/react-native-confirmation-code-field#234]
Im not able to copy paste a code. The paste context menu wont show up on mobile when long clicking on the code field

**Comment by retyui** [comment]
does it help? 
https://github.com/retyui/react-native-confirmation-code-field/blob/c944750acb811d2cc7f2a45ae9e6982831297419/src/CodeField.tsx#L77-L79

**Comment by oliviercperrier** [comment]
> does it help?
> 
> https://github.com/retyui/react-native-confirmation-code-field/blob/c944750acb811d2cc7f2a45ae9e6982831297419/src/CodeField.tsx#L77-L79

@retyui Doesn't seem to work on the web on a mobile device

**Comment by oliviercperrier** [comment]
Okay so the reason why it was not working it that i set the opacity of the input to 0.
I need to keep it to at least 0.011 but im seing the original input value at that opacity. So i used this:

```
      textInputStyle={{
        color: "transparent"
      }}
``` 

And it seems to fix this issue. Not sure thats the best but its working tho.
