### ISSUE TITLE
How to dynamically set the Input box?

### ISSUE THREAD

**Issue by tmKnight01** [retyui/react-native-confirmation-code-field#240]
I am very happy to use such a great library, but my needs are somewhat special. I need to dynamically change the position of the Input. There are three Inputs. I implemented this function, but the input box focus can only automatically jump to the next one instead of jumping to the actual input. What should I do?
 I listed my code.
![image](https://github.com/retyui/react-native-confirmation-code-field/assets/94892258/fe1218a7-f357-487c-91ee-ead4fbfabbfe)

`
  const CELL_COUNT = 8;
const FillBlock = useCallback(() => <View style={styles.block} />, []);
  const [value, setValue] = useState('');
  const ref = useBlurOnFulfill({value, cellCount: CELL_COUNT});
 const route = useRoute();
  const {pwdIndex = [1, 2, 3] as number[]} = route.params as any;
  
    const textChild = ({symbol, isFocused}: RenderCellOptions) => {
    if (symbol) {
      return '•';
    } else if (isFocused) {
      return <Cursor />;
    }
    return null;
  };
  
    const renderCallBox = ({index, symbol, isFocused}: RenderCellOptions) => {
    if (index == 6) {
      return (
        <>
          <Icon
            key={index + Date.now()}
            name="more-horizontal"
            size={32}
            color={'#ABABAB'}
          />
          {pwdIndex.includes(index + 1) ? (
            <AppText
              key={value-${index}}
              style={[styles.cell, isFocused && styles.focusCell]}
              onLayout={getCellOnLayoutHandler(index)}>
              {textChild({index, symbol, isFocused})}
            </AppText>
          ) : (
            <FillBlock />
          )}
        </>
      );
    }
    if (pwdIndex.includes(index + 1))
      return (
        <AppText
          // key={value-${index}}
          style={[styles.cell, isFocused && styles.focusCell]}
          onLayout={getCellOnLayoutHandler(index)}>
          {textChild({index, symbol, isFocused})}
        </AppText>
      );
    return <FillBlock />;
  };
        <CodeField
            ref={ref}
            {...props}
            value={value}
            autoFocus={true}
            onChangeText={setValue}
            cellCount={CELL_COUNT}
            rootStyle={styles.flexRow}
            keyboardType="number-pad"
            textContentType="oneTimeCode"
            renderCell={renderCallBox}
          />
  
  `
  
 can give  me some tips?,   many thansk!!

**Comment by retyui** [comment]
you can use a multiple CodeFields and move focus between them 

also as it's not an issue I'm closing it
