### ISSUE TITLE
 keyboard is not hide when user complete the code

### ISSUE THREAD

**Issue by iamharisdev** [retyui/react-native-confirmation-code-field#242]
### in android and ios both side keyboard not hide even user complete the code

**Comment by retyui** [comment]
if you use an useBlurOnFulfill hook blur event should be called when `value` will has `cellCount` length 

 `const ref = useBlurOnFulfill({value, cellCount: CELL_COUNT});`

https://github.com/retyui/react-native-confirmation-code-field/blob/9fc89c213eedb355f8bde2e04b0da23a55a4710e/src/useBlurOnFulfill.ts#L13-L17
