### ISSUE TITLE
Unable to autofill code with sms code

### ISSUE THREAD

**Issue by matanelgabsi** [retyui/react-native-confirmation-code-field#25]
Hi there,
First of all - Love your work. This library saved me a lot of time :)
I currently have an issue with it - when I try to "paste" a code using the SMS code autocomplete (when you receive a code via SMS, and you can press on in like other auto complete suggestions), I get the wrong code.
Tried to debug it a bit, and it seems that handlerOnChangeText receives the code one char at a time, but as a whole. for example, if the code is 123456. then the text will be 1 for the first time, 12 for the second, 123 for the third etc.
As a workaround, I've changed `text = text[0];` to `text = text[text.length - 1];` (and changed maxLength to code length) but this is probably not the best idea..
BTW, tried canPasteCode but as you can understand it didn't solve the issue.
Any ideas?

Thanks!

**Comment by retyui** [comment]
IOS ?

**Comment by matanelgabsi** [comment]
Oh sorry, yes :)

**Comment by retyui** [comment]
I do not have such devices to test the problem, but no one bothers you to create a PR

**Comment by retyui** [comment]
> BTW, tried canPasteCode but as you can understand it didn't solve the issue

it is rather strange, just for this feature this flag was developed

**Comment by gangadhartinmen** [comment]
![savingfromsms](https://user-images.githubusercontent.com/28722992/49855358-0108fc80-fe13-11e8-8d59-d5da69544bec.gif)

Facing the same problem in IOS when copying through SMS.
Could any one help me, to solve this?

**Comment by gangadhartinmen** [comment]
It is getting pasted in 1st block with 3 dot symbols.

**Comment by retyui** [comment]
https://github.com/retyui/react-native-confirmation-code-field/pull/26

**Comment by gangadhartinmen** [comment]
Thanks. Will test it by today EOD and let you know.

**Comment by matanelgabsi** [comment]
Hi @retyui , tested it now, and it works!
but for some reason this version broke something for me. I can't add a placeholder for the input. I define:

`inputProps={{
                  placeholder: "-",
                  style: {
                    fontSize: 16
                  },
                  placeholderTextColor: "#1E2B66"
                }}`

Am I missing something?

thank you!

**Comment by gangadhartinmen** [comment]
![otp_ios_save](https://user-images.githubusercontent.com/28722992/50592789-9ef46200-0ebb-11e9-87ea-a517b4ec87f0.gif)

**Comment by gangadhartinmen** [comment]
Thank you so much. Its working.

**Comment by retyui** [comment]
Thanks for your feedback
The component got better thanks to you

**Comment by dhavalpanchani** [comment]
@retyui : Good job, Keep it up. I was looking for the autofill SMS, I think I can use this.

**Comment by mariomurrent-softwaresolutions** [comment]
Should this also work for Android?

**Comment by retyui** [comment]
@mariomurrent-softwaresolutions 

For the Android platform, you can use an SMS listener, to insert code 

- https://github.com/wolfgio/react-native-android-sms-verification
- https://github.com/RobertBonfada/react-native-sms-receiver
- ...

**Comment by mariomurrent-softwaresolutions** [comment]
Hmm well this will probably not well with Expo, right?

**Comment by retyui** [comment]
I didn't find API in the docs, Someone requested this feature (see https://forums.expo.io/t/built-in-android-ios-sms-listener/19361/2)

**Comment by summerkiflain** [comment]
How does this thing works with iOS, I am not getting "From Messages XXXX" above may iPhone numeric keyboard. do I need to send my message in some specific format for iOS also?

**Comment by mariomurrent-softwaresolutions** [comment]
> How does this thing works with iOS, I am not getting "From Messages XXXX" above may iPhone numeric keyboard. do I need to send my message in some specific format for iOS also?

Same applies for me

**Comment by summerkiflain** [comment]
> > How does this thing works with iOS, I am not getting "From Messages XXXX" above may iPhone numeric keyboard. do I need to send my message in some specific format for iOS also?
> 
> Same applies for me

I figured this out, you have to have OTP in message text for iOS numeric keyboard to pick it up.

**Comment by mariomurrent-softwaresolutions** [comment]
What does OTP mean?

**Comment by mateodaza** [comment]
> What does OTP mean?

one time password

**Comment by mariomurrent-softwaresolutions** [comment]
> > > How does this thing works with iOS, I am not getting "From Messages XXXX" above may iPhone numeric keyboard. do I need to send my message in some specific format for iOS also?
> > 
> > 
> > Same applies for me
> 
> I figured this out, you have to have OTP in message text for iOS numeric keyboard to pick it up.

So how does your SMS look like that it gets picked up?

**Comment by Stevemoretz** [comment]
Hi, recently Android seems to support this too according to: https://stackoverflow.com/a/71386603/10268067 so you'd need to set [autocomplete](https://reactnative.dev/docs/textinput#autocomplete-android) to sms-otp for android to work the same way as iOS does, have you done this interanlly?
