### ISSUE TITLE
variant border-b is not work

### ISSUE THREAD

**Issue by hoavo** [retyui/react-native-confirmation-code-field#28]
```
<CodeInput
                variant="border-b"
                space={10}
                size={50}
                cellBorderWidth={2}
                activeColor="white"
                inactiveColor="rgba(255, 255, 255, 0.25)"
                inputPosition="center"
                onFulfill={value => this.setState({ otp: value })}
              />
```

The border of Cell does not appear

**Comment by retyui** [comment]
Can you show me a screenshot,  and what version do you use?

**Comment by hoavo** [comment]
![screen shot 2019-01-04 at 00 09 22](https://user-images.githubusercontent.com/2727930/50651121-02ae8600-0fb5-11e9-8893-817d6d979c68.png)
```
react-native-confirmation-code-field": "^3.0.0",
```

**Comment by retyui** [comment]
Is it a simulator?

**Comment by retyui** [comment]
I create a simple example to understand the problem:
https://snack.expo.io/@retyui/thoughtful-cashew

it is a problem from react native and only in IOS

**Comment by retyui** [comment]
But it's the only emulator. I will test this bug on real deviсe later

**Comment by hoavo** [comment]
Thanks @retyui, i tested on real device, it's so weird

**Comment by retyui** [comment]
@hoavo 
Try to use the next version and will tell me it's work or not
```
yarn add react-native-confirmation-code-field@next
```

**Comment by hoavo** [comment]
@retyui Thanks, it's working fine.
