### ISSUE TITLE
Issue with testID

### ISSUE THREAD

**Issue by jeremybdk** [retyui/react-native-confirmation-code-field#38]
Hello,
I'm trying to add a testID to my CodeInput but it's not working, it seems that it's not added to the input nor anywhere else in the view.

Here is my code:

`<CodeInput
     ref="codeInput"
     activeColor='rgba(0, 0, 0, 1)'
     codeLength={4}
     keyboardType="number-pad"
     inactiveColor='rgba(0, 0, 0, 1.3)'
     autoFocus={true}
     inputPosition='center'
     testID="code_input"
     size={56}
     onFulfill={(code) => this._onFinishCheckingCode1(code)}
     containerProps={{ marginTop: 20 }} />`

Am I doing something wrong?
Thanks in advance :)

**Comment by retyui** [comment]
@jeremybdk 
Do you use end-to-end tests?

**Comment by jeremybdk** [comment]
Yes I do with Detox

**Comment by retyui** [comment]
Fixed in [3.2.1](https://github.com/retyui/react-native-confirmation-code-field/blob/master/CHANGELOG.md#321)

**Comment by jeremybdk** [comment]
Thanks a lot :)

**Comment by retyui** [comment]
@jeremybdk 
```js
// is wrong
containerProps={{ marginTop: 20 }}
// use it
containerProps={ style: { marginTop: 20 } }
```

**Comment by jeremybdk** [comment]
Unfortunately I don't think it's working,

>                 <CodeInput
                    ref="codeInput"
                    activeColor='rgba(0, 0, 0, 1)'
                    codeLength={4}
                    defaultCode={1111}
                    keyboardType="number-pad"
                    inactiveColor='rgba(0, 0, 0, 1.3)'
                    autoFocus={true}
                    inputPosition='center'
                    size={56}
                    testID='code_input'
                    onFulfill={(code) => this._onFinishCheckingCode1(code)}
                    inputProps={ {style: { marginTop: 20 }, testID: "code_input_props"} } 
                    containerProps={ {style: { marginTop: 20 }, testID: "code_container_props"} } />

I cand find both code_input_props and code_container_props but code_input is still not in the view ...

**Comment by retyui** [comment]
Try to use  [`nativeID`](https://facebook.github.io/react-native/docs/view#nativeid)
```js
<CodeInput. 
   inputProps={ {style: { marginTop: 20 }, nativeID: "code_input_props"} }   
   containerProps={ {style: { marginTop: 20 }, nativeID: "code_container_props"} } 
/>
```

**Comment by jeremybdk** [comment]
Well it's still working, the issue I am facing is wit the testID in the CodeInput directly as it's not sent to the view, the one in inputProps and containerProps are working as expected.

**Comment by siliconavengers** [comment]
Any answer? I'm using detox and facing same issue.
