### ISSUE TITLE
Focus Order Issue

### ISSUE THREAD

**Issue by beastfromthefareast** [retyui/react-native-confirmation-code-field#40]
Thanks for the update to support cell props, was very helpful! 

I have a new problem now that I've been trying to fix for the last day and a half, but can't figure out. The TextInputCustom gets pinched between the 1st and 3rd Cell when I'm going through it with the screen reader focus. The 2nd cell gets pushed out to the end. 

So when I focus it goes like this:
Cell 1, TextInputCustom, Cell 3, Cell 4, Cell 5, Cell 6, Cell 7, Cell 2

Tried working around it with tab index and aria-hidden but it hasn't worked. I thought maybe it was a render order issue and tried doing converting it into async, but couldn't get that working ( still a beginner here). The last idea I have is to add an offset option to so that the element moves out of the way, but the findindex and other functions compensate for the offset position.

**Comment by retyui** [comment]
Try this:
```js
         <CodeInput
            onFulfill={this.handlerOnFulfill}
            cellProps={{accessibilityRole: 'none'}}
        />
```

**Comment by beastfromthefareast** [comment]
Didn't seem to have an effect. However, I managed to make it work by shrinking the textInputCustom vertically slightly, now the screen reader focuses in the correct order while still being touchable.

**Comment by retyui** [comment]
In feature I will replace [<TextInput />](https://github.com/retyui/react-native-confirmation-code-field/blob/5dae0420e39bf1db09a2227d8083ff5322ebfc8b/src/components/Cell.js#L28) to `<Text />`
You should not interact with these Cells
