### ISSUE TITLE
Cannot Focus Code Input Cell once all fields are populated

### ISSUE THREAD

**Issue by reedyrm** [retyui/react-native-confirmation-code-field#44]
Thank you for getting out a fix to #32   I'm just now getting back into my mobile app and updating all dependencies.

When AutoFocus=true, everything is working as intended, but I'm running into a scenario where once all the inputs are populated, I cannot select the input again.  

My scenario is where I typo the last number, I cannot select it and delete it.  I have to either add a clear button for the entire code or submit it with a wrong code.  I understand the push towards pasting code from SMS, but not all devices that I'm working with have SIM cards.

**Comment by retyui** [comment]
Can you create video to understand problem?

**Comment by reedyrm** [comment]
I can type in and delete each part of the code, but once the entire code is populated.  I'm unable to change the code.  

Here is a link to a video to show the problem:
https://s3.amazonaws.com/quickbite-static-resources/videos/CodeFieldLastInput.mov

**Comment by retyui** [comment]
I taste about this problem, this problem can only be found on the emulator
