### ISSUE TITLE
How to set input to accept only numerics?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [retyui/react-native-confirmation-code-field#47]
How to set input to accept only numerics?

**Comment by retyui** [comment]
Read a documentation

**Comment by ManigandanRaamanathan** [comment]
@retyui there are no mention of the numeric validation in text input

**Comment by retyui** [comment]
@ManigandanRaamanathan try this https://github.com/retyui/react-native-confirmation-code-field/pull/41#issuecomment-465217446

**Comment by ManigandanRaamanathan** [comment]
@retyui that solution throws error:-

![](https://user-images.githubusercontent.com/22089729/54880595-38129380-4e81-11e9-81cd-3b934190f3ab.png)

**Comment by retyui** [comment]
@ManigandanRaamanathan 
Show me your code!

**Comment by ManigandanRaamanathan** [comment]
@retyui

**Comment by ManigandanRaamanathan** [comment]
@retyui 

First I'm creating a new class 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/22089729/54926396-32818000-4f4b-11e9-919e-743fece339b9.png">

Then instead of calling the <CodeInput /> library, I'm calling <CustomCodeInput />
<img width="622" alt="image" src="https://user-images.githubusercontent.com/22089729/54926490-5f359780-4f4b-11e9-8b9f-bd965fbcf412.png">


Then the red error screen says undefined is not and object...

**Comment by retyui** [comment]
@ManigandanRaamanathan Try to remove the line `containerProps={ ... }`

**Comment by ManigandanRaamanathan** [comment]
@retyui 
I'm getting this error now
<img width="299" alt="image" src="https://user-images.githubusercontent.com/22089729/54927043-67da9d80-4f4c-11e9-90af-23d29e78b807.png">

**Comment by retyui** [comment]
@ManigandanRaamanathan 
You have some syntax error. create an example in https://snack.expo.io
it will be better than screenshots

**Comment by retyui** [comment]
@ManigandanRaamanathan 
You have some syntax error. create an example in https://snack.expo.io
it will be better than screenshots

**Comment by ManigandanRaamanathan** [comment]
@retyui is it working on your end with the above given codes?

**Comment by retyui** [comment]
@ManigandanRaamanathan  I don't care about `given codes`! 
I need a working example to understand where you make a mistake!

**Comment by ManigandanRaamanathan** [comment]
@retyui this is the snack link https://snack.expo.io/SJYGLwLdE  Please go through

**Comment by ManigandanRaamanathan** [comment]
@retyui when you launch the app on the snack, it throws the same error

**Comment by retyui** [comment]
@ManigandanRaamanathan 
[3.3.0](https://github.com/retyui/react-native-confirmation-code-field/blob/master/CHANGELOG.md#330)

**Comment by ManigandanRaamanathan** [comment]
@retyui works great. Below is the code:-

`normalizeCode={(code)=>{
          const numbers = code.match(/\d+/g);

          return (Array.isArray(numbers) ? numbers.join('') : '')
}}`

**Comment by partitect** [comment]
value={value.replace(/\D/g, '')}

` <CodeField
            ref={ref}
            {...props}
            value={value.replace(/\D/g, '')}
            onChangeText={setValue}
            cellCount={CELL_COUNT}
            rootStyle={styles.codeFieldRoot}
            keyboardType="numeric"
            //textContentType="oneTimeCode"
            renderCell={renderCell}
          />`
