### ISSUE TITLE
How set code to a state onTextChange?

### ISSUE THREAD

**Issue by farshidshahmoradi1996** [retyui/react-native-confirmation-code-field#48]
how can set code to a state onTextChange?
like normal inputs

**Comment by retyui** [comment]
Maybe it can help https://github.com/retyui/react-native-confirmation-code-field/pull/36#issuecomment-462644571

**Comment by farshidshahmoradi1996** [comment]
thanks @retyui  
but yet i can't set code to state onTextChange 
please give me an example onTextChange Set it to a State
like this:
`  <TextInput onChangeText={(text) => this.setState({text})} />`

**Comment by retyui** [comment]
The 'react-native-confirmation-code-field'  is stateful component
You can't do it

**Comment by farshidshahmoradi1996** [comment]
So how can control the entry code?
with onFulfill can but if user delete the entry code what ?
I have a button to check the entry code 
this button is disabled default
when the code FulFill this button enabled 
but i want when the entry code deleted this button disabled again
have you any idea?

**Comment by retyui** [comment]
```js
import React, { Component } from 'react';
import CodeInput from 'react-native-confirmation-code-field';

class App extends Component {
  handlerOnFulfill = code => console.log(code);

  render() {
    return <CodeInput 
       inputProps={ {onTextChange: text => console.log(text) } }
       onFulfill={this.handlerOnFulfill}
    />;
  }
}

```

**Comment by farshidshahmoradi1996** [comment]
Thanks alot

**Comment by neiker** [comment]
@retyui: your solution will not work because `onTextChange` does not exists (it's `onChangeText` actually) and even if you change it to `onChangeText` will not work because its overwritted. 
My solution is:
```js
       inputProps={{
          // context menu is buggy on iOS because there's and hidden input
          contextMenuHidden: true,
          onChange: (ev) => {
            console.log(ev.nativeEvent.text);
          },
        }}
```
