### ISSUE TITLE
Android keyboard back button is not clearing the text

### ISSUE THREAD

**Issue by kevinhury** [retyui/react-native-confirmation-code-field#5]

**Comment by retyui** [comment]
Can provide more information, or a demo?

**Comment by samitha9125** [comment]
This works fine for me in Android Emulator (Nexus 5 API 26)

**Comment by retyui** [comment]
@samitha9125 
if there is no problem, can I close the issue?

**Comment by retyui** [comment]
@kevinhury 
Can we send `react-native info` output ?

**Comment by kevinhury** [comment]
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.6.0
  npm: 5.4.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

**Comment by retyui** [comment]
@kevinhury 
Removing characters based on the `onkeypress` handler

And I checked the documents for the old version : https://facebook.github.io/react-native/docs/0.52/textinput#onkeypress. `onkeypress` handler not supported for Android.
