### ISSUE TITLE
Invariant Violation: input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

### ISSUE THREAD

**Issue by kations** [retyui/react-native-confirmation-code-field#50]
Hi,
I tried to use this package with the latest version of react-native-web but this error occurred while rendering:

Invariant Violation: input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
    in input (created by TextInput)
    in TextInput (at Cell.js:29)

Would be great if it would work in web too. Used ist with the expo web alpha.
Thanks

**Comment by retyui** [comment]
@kations The latest version doesn't support `react-native-web` 
Use 2.x

**Comment by murtraja** [comment]
@retyui, can you give a rough outline of what needs to be done so that it works for web as well? I don't want to use different versions for web and native.

**Comment by retyui** [comment]
No, I can't

**Comment by murtraja** [comment]
#52 this doesn't have blinking cursor support, but in Firefox  and Android, this works (will let you know after testing iOS too)

**Comment by retyui** [comment]
@kations Good news [3.4.0]( https://github.com/retyui/react-native-confirmation-code-field/blob/master/CHANGELOG.md#340)
