### ISSUE TITLE
Animated example failed to show Verification button and input keyboard

### ISSUE THREAD

**Issue by emclab** [retyui/react-native-confirmation-code-field#58]
I am copying the animated example code from https://github.com/retyui/react-native-confirmation-code-field/blob/master/examples/src/realDemo/AnimatedExample/README.md. But there are a few issues. I don't understand how exactly the code works. Here is the animated scrren on android:

![Capture](https://user-images.githubusercontent.com/946013/56461753-b5d89a80-636c-11e9-8498-427c46e1dcf4.JPG)

Mine is missing Verification button and also clicking the code box does not enable the input keyboard. I think I copy the exact code. Here is my code (except a few name changes):

export default class Verif extends React.Component {
    static navigationOptions = {
      title:  '核对验证码'
    }; 

    /* constructor(props) {
        super(props);
        console.log("Props in Verif : ", this.props);
        
        this.state = {
          
        };
    }; */

    _animationsColor = [...new Array(codeLength)].map(
        () => new Animated.Value(0),
      );
    _animationsScale = [...new Array(codeLength)].map(
    () => new Animated.Value(1),
    );
    
    onFinishCheckingCode = code => {
        if (code !== '1234') {
          return Alert.alert(
            'Confirmation Code',
            'Code not match! Try 1234',
            [{ text: 'OK' }],
            { cancelable: false },
          );
        }
    
        Alert.alert('Confirmation Code', 'Successful!', [{ text: 'OK' }], {
          cancelable: false,
        });
    };
    
    animateCell({ hasValue, index, isFocused }) {
        Animated.parallel([
          Animated.timing(this._animationsColor[index], {
            toValue: isFocused ? 1 : 0,
            duration: 250,
          }),
          Animated.spring(this._animationsScale[index], {
            toValue: hasValue ? 0 : 1,
            duration: hasValue ? 300 : 250,
          }),
        ]).start();
    }
    
    cellProps = ({ hasValue, index, isFocused }) => {
        const animatedCellStyle = {
          backgroundColor: hasValue
            ? this._animationsScale[index].interpolate({
                inputRange: [0, 1],
                outputRange: [NOT_EMPTY_CELL_BG_COLOR, ACTIVE_CELL_BG_COLOR],
              })
            : this._animationsColor[index].interpolate({
                inputRange: [0, 1],
                outputRange: [DEFAULT_CELL_BG_COLOR, ACTIVE_CELL_BG_COLOR],
              }),
          borderRadius: this._animationsScale[index].interpolate({
            inputRange: [0, 1],
            outputRange: [CELL_SIZE, CELL_BORDER_RADIUS],
          }),
          transform: [
            {
              scale: this._animationsScale[index].interpolate({
                inputRange: [0, 1],
                outputRange: [0.2, 1],
              }),
            },
          ],
        };
    
        // Run animation on next event loop tik
        // Because we need first return new style prop and then animate this value
        setTimeout(() => {
          this.animateCell({ hasValue, index, isFocused });
        }, 0);
    
        return {
          style: [styles.input, animatedCellStyle],
        };
    };
    
    containerProps = { style: styles.inputWrapStyle };

    render() {
        return (
            <View style={styles.inputWrapper}>
              <Text style={styles.inputLabel}>Verification</Text>
              <Image style={styles.icon} source={source} />
              <Text style={styles.inputSubLabel}>
                {'输入短信收到的验证码'}
              </Text>
              <CodeFiled
                maskSymbol="*"
                variant="clear"
                codeLength={codeLength}
                keyboardType="numeric"
                cellProps={this.cellProps}
                containerProps={this.containerProps}
                onFulfill={this.onFinishCheckingCode}
                CellComponent={Animated.Text}
              />
              <View style={styles.nextButton}>
                <Text style={styles.nextButtonText}>Verify</Text>
              </View>
            </View>
        );
    }
}

What I am missing here?

**Comment by tylerolechnowicz** [comment]
Hello, I am having this same issue. Using the animated example as a reference, when I click on the cells, the keyboard does not pop up so I can input anything. Please help!
