### ISSUE TITLE
No way for autofocus to be true when default input has a value set

### ISSUE THREAD

**Issue by brockmartin** [retyui/react-native-confirmation-code-field#60]
I have autofocus set to true which works great, however when I add default input value autofocus doesn't work.  Would love to be able to set a placeholder for the input cell or have the default input value to act like palceholders instead of block autofocus because it thinks all cells are filled.

**Comment by retyui** [comment]
what default value do you use?

**Comment by brockmartin** [comment]
‘●’    <—— that 

I can use something like this right?  

inputProps={{ placeholder: '*' }}

**Comment by retyui** [comment]
How about this prop 
https://github.com/retyui/react-native-confirmation-code-field/blob/master/docs/API.md

**Comment by brockmartin** [comment]
sorry super green to all this what am I looking for specifically in the docs to add some placeholder text to each cell

**Comment by retyui** [comment]
I don't understand very well what the problem is

**Comment by brockmartin** [comment]
nvm
