### ISSUE TITLE
Include blurOnSubmit prop

### ISSUE THREAD

**Issue by leozzitowned** [retyui/react-native-confirmation-code-field#61]
When I complete the code, I would like to keep the focus in the input.

Is it possible to do without .focus()? Because it generates a keyboard flicking.

Thanks for the component, by the way.

**Comment by retyui** [comment]
> without .focus()?


What do you mean?

**Comment by leozzitowned** [comment]
I mean, when the user completes the input, the only way to keep the focus on input is calling this.ref.focus() after the submit. But this causes a flick on the screen.

I made a PR for reference, but there was supposed to be a way to control blurOnSubmit.

https://github.com/retyui/react-native-confirmation-code-field/pull/62
