### ISSUE TITLE
Add an option to disable the cursor

### ISSUE THREAD

**Issue by humbkr** [retyui/react-native-confirmation-code-field#63]
Hello,

Would it be possible to add an option to disable the cursor?
I currently have a design that is completely doable with your library, except for this small feature.
I think it would be interesting to have this option, as UX-wise using activeColor and inactiveColor can already by themselves indicate to the user which cell is active.

**Comment by retyui** [comment]
You can extend current component

```js
import CodeInput from 'react-native-confirmation-code-field';

class MyCodeInput extends CodeInput {
	renderCursor(){
		const {shouldRenderCursor} = this.props;

		if(shouldRenderCursor){
			return super.renderCursor();
		}

		return null;
	}
}

<MyCodeInput  shouldRenderCursor={false} />
```
