### ISSUE TITLE
Text and cursor are misaligned when using big font sizes

### ISSUE THREAD

**Issue by humbkr** [retyui/react-native-confirmation-code-field#64]
Hello,

Using basic options + custom styling with cellProps={{ style: {} }} to change the font size, I have strange behaviours on Android and iOS.

**iOS**
Small font: OK
<img width="226" alt="Screenshot 2019-05-24 at 17 34 35" src="https://user-images.githubusercontent.com/845297/58340059-406c5800-7e4b-11e9-8d87-673393356503.png">

Big font: KO, the cursor is not vertically centered
<img width="250" alt="Screenshot 2019-05-24 at 17 32 35" src="https://user-images.githubusercontent.com/845297/58340081-4feba100-7e4b-11e9-94f7-9256e1b546ee.png">

**Android**
Small font: OK
![Screenshot_20190524-174553](https://user-images.githubusercontent.com/845297/58340469-3c8d0580-7e4c-11e9-898a-cef5af7a220a.png)

Big font: KO, the text is cropped and the cursor is misaligned
![Screenshot_20190524-175340](https://user-images.githubusercontent.com/845297/58340808-000dd980-7e4d-11e9-961d-ee0a073f59bf.png)

I tried to play with padding, lineHeight, and other props, but without success.

**Comment by retyui** [comment]
You can use `lineHeight` to fix differences between platforms
