### ISSUE TITLE
Is it support auto read OTP when I receive OTP from SMS?

### ISSUE THREAD

**Issue by getinfyKiranreddy** [retyui/react-native-confirmation-code-field#65]
I am using this repo and it works super fine but I want to create auto read OTP when I receive OTP from SMS?

Please let me know how to create auto read OTP ?

Thanks

**Comment by retyui** [comment]
For example, you can use [sms listener](https://www.npmjs.com/package/react-native-android-sms-listener) and then [insert the received code](https://github.com/retyui/react-native-confirmation-code-field#how-paste-or-clear-code)
