### ISSUE TITLE
How to get the keyboard back after dismiss()?

### ISSUE THREAD

**Issue by chadhobson** [retyui/react-native-confirmation-code-field#66]
I've got a TouchableWithoutFeedback that dismisses the keyboard. If this happens, and I click on the first input box for the code, the keyboard doesn't come back and I can't input again.

What am I missing?

**Comment by retyui** [comment]
Perhaps you should use '.focus()' or '.blur()' methods

**Comment by chadhobson** [comment]
I got it working. 

I had originally wrapped the <CodeInput> inside a <TouchableWithoutFeedback> but the onPress wasn't getting picked up. I ended up moving the <TouchableWithoutFeedback> **below** the <CodeInput> and absolute positioned it so it would be full screen, effectively overlaying a View on top of the <CodeInput> which picks up the OnPress now. 

I'm getting the effect I want but it's janky, as RN can be.
