### ISSUE TITLE
Cannot get code field to focus (or respond to any gestures)

### ISSUE THREAD

**Issue by felixchan** [retyui/react-native-confirmation-code-field#67]
I cloned the Red Example.  I can't seem to get the field to focus.

```
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-confirmation-code-field": "^3.6.0",
```

**Comment by retyui** [comment]
Can you provide an example for this problem and code ?

**Comment by ssg-luke** [comment]
Yep same, I tried the Animated example

**Comment by ssg-luke** [comment]
OK yep I figured it out. This component does not play well with Flexbox. If its inside a flex:1 container the text inputs will fill the entire screen. Quickest way to solve that is to wrap the component in a <View /> with a fixed height (based on your cell height etc)

**Comment by retyui** [comment]
containerProps
You can use to pass custom style

**Comment by ssg-luke** [comment]
So I was actually doing that already with the style from the animated example i.e.
```
inputWrapStyle: {
    height: CELL_SIZE,
    marginTop: 30,
    paddingHorizontal: 20,
    justifyContent: 'space-between',
  },
```
This still causes massive issues if not wrapped in an parent <View /> with height: CELL_SIZE.

**Comment by retyui** [comment]
@ssg-luke 
Can you create an example on https://snack.expo.io/,  to show your problem?
