### ISSUE TITLE
Cursor should not inherit all styles from cell.

### ISSUE THREAD

**Issue by neiker** [retyui/react-native-confirmation-code-field#71]
Hi! I need the cell text to be semi bold, but when `fontWeight` is set to cell, also is applied to `Cursor` component. So I need to apply this hack:
```js
cellProps={({ hasValue }) => ({
          style: {
              fontWeight: hasValue ? '500' : '300' 
          },
        })}
```

**Comment by retyui** [comment]
That is a good point 👍
It will be fixed

**Comment by ETLopes** [comment]
Why this change was reverted?

**Comment by retyui** [comment]
Hi  @ETLopes 
The latest version conceptually different. The main idea was to give developers a flexible API without limitation.

As result it really easy to create different types of code fields
- [Animated variant](https://github.com/retyui/react-native-confirmation-code-field/tree/master/examples/DemoCodeField/src/AnimatedExample)
- [Formatting example](https://github.com/retyui/react-native-confirmation-code-field/tree/master/examples/DemoCodeField/src/FormattingExample)
...

So to manipulate this behavior you should take it into your hands:
```js

const styles = StyleSheet.create({
  resetFontStyles: {
    backgroundColor: '#00000000',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecorationLine: 'none',
    textTransform: 'none',
  },
});



//...
     <CodeField
        renderCell={({index, symbol, isFocused}) => (
          <Text
            key={index}
            style={[styles.cell, isFocused && styles.focusCell]}
            onLayout={getCellOnLayoutHandler(index)}>
                                                  // just add a wrapper to reset cell styles
            {symbol || (isFocused ? <Text style={styles.resetFontStyles}><Cursor /></Text> : null)}
          </Text>
        )}

```
