### ISSUE TITLE
"textTransform" is not a valid style property.

### ISSUE THREAD

**Issue by booboothefool** [retyui/react-native-confirmation-code-field#73]
Hi I am getting the following error when trying to import the library.
```
import CodeInput from 'react-native-confirmation-code-field';
```

![Simulator Screen Shot - iPhone 8 - 2019-08-19 at 02 28 40](https://user-images.githubusercontent.com/13257645/63243727-6a0a0500-c229-11e9-82e0-b9282355b452.png)

**Comment by retyui** [comment]
@booboothefool Can you tell me what version of `react-native` do you use?

**Comment by booboothefool** [comment]
@retyui I am on Expo 30 which uses React Native 0.55.4. Expo is giving me a lot of trouble trying to upgrade - I always try and give up! But thank you, `react-native-confirmation-code-field@3.7.0` works great for me! 👍
