### ISSUE TITLE
`tmpVsmwGj` was published in 3.7.1

### ISSUE THREAD

**Issue by giautm** [retyui/react-native-confirmation-code-field#74]
When I installed version `3.7.1` with `yarn`, in `node_modules/react-native-confirmation-code-field` It contain an folder as named `tmpVsmwGj`.  Content of that folder look like version 3.7.0 

<img width="383" alt="Screen Shot 2019-08-20 at 1 04 47 AM" src="https://user-images.githubusercontent.com/12751435/63288299-891a9c80-c2e6-11e9-97f4-9212ddeeb156.png">
<img width="383" alt="Screen Shot 2019-08-20 at 1 08 00 AM" src="https://user-images.githubusercontent.com/12751435/63288469-fb8b7c80-c2e6-11e9-9dc7-a382e121af11.png">

Is this a mistake in publishing progress?

**Comment by retyui** [comment]
Yes , it is

**Comment by retyui** [comment]
fixed in `3.9.0`

**Comment by giautm** [comment]
Cool, everything worked well. <3
