### ISSUE TITLE
Thanks team, but please give change number of cell input ? have a props so i don't know that ?

### ISSUE THREAD

**Issue by TranVanThaiSon** [retyui/react-native-confirmation-code-field#76]

**Comment by retyui** [comment]
@TranVanThaiSon 
Docs: https://github.com/retyui/react-native-confirmation-code-field/blob/master/docs/API.md

**Comment by TranVanThaiSon** [comment]
thanks you, I think you should public it on document in npm page or
git.readme

Vào Th 4, 21 thg 8, 2019 vào lúc 15:10 undefined <notifications@github.com>
đã viết:
