### ISSUE TITLE
Release  verison blank screen

### ISSUE THREAD

**Issue by MaximovAlexander** [retyui/react-native-confirmation-code-field#77]
In debug version all is displayed correctly, but when compiled APK is only displayed blank screen.
version RN 0.60

**Comment by retyui** [comment]
Could you provide demo repository?

**Comment by AdrianBordeianu** [comment]
Same problem for react-native 0.58.5.

**Comment by retyui** [comment]
So anyone can provide a demo repo?

**Comment by retyui** [comment]
@AdrianBordeianu 
@MaximovAlexander 
Hi!
Can we provide a demo app?
