### ISSUE TITLE
Cannot Focus on Input my Manually Pressing

### ISSUE THREAD

**Issue by tylerolechnowicz** [retyui/react-native-confirmation-code-field#78]
Hello,

I cannot focus on the input by manually pressing it, I have to instead set autoFocus={true}, but when I clear the input fields with the clear() function and then try to re-focus with focus() it does not focus.

Can you please explain why manually clicking on the input fields does not focus?

**Comment by retyui** [comment]
Try to debug this code
https://github.com/retyui/react-native-confirmation-code-field/blob/03525ae7982953243afc690b3d20ec14e72af154/src/components/ConfirmationCodeInput/ConfirmationCodeInput.js#L198-L200

**Comment by oskarszoon** [comment]
I have the same issue of not being able to click on the code input, but only when used inside a native modal. When the input is on a regular screen, all is fine.

**Comment by retyui** [comment]
@oskarszoon can you create a [snack](https://snack.expo.io/) with modal variant?

**Comment by LPranulis** [comment]
Same issue

**Comment by poison** [comment]
Had the same issue, but for me setting the prop autoFocus to true did the trick

**Comment by retyui** [comment]
Hey,
I repeat my question)
Someone can create demo with this bag ?

**Comment by poison** [comment]
I've created https://github.com/poison/issue78 to demonstrate this issue (which was a clean project). Didn't get it working on snack since I couldn't import the module

**Comment by retyui** [comment]
Thanks!

**Comment by retyui** [comment]
@poison
It problem on iOS and Android?

**Comment by powernic** [comment]
@retyui I have the same error on iOS.

**Comment by poison** [comment]
Seems to work on Android, but not on iOS

**Comment by powernic** [comment]
This works when the height of the parent block is set.
`<View style={{height:40}}> <CodeInput /></View>`

**Comment by retyui** [comment]
Thanks a lot @poison!

Fixed in `4.0.0`

Diff [3.9.0 => 4.0.0](https://npmfs.com/compare/react-native-confirmation-code-field/3.9.0/4.0.0/)

**Comment by marcorm** [comment]
@retyui unfortunately it seems to be an issue again with RN 0.62.2 (on 0.62.1 it works fine!).
To reproduce the error i just download the Example from this repo and upgrade to RN 0.62.2.

**Comment by retyui** [comment]
@marcorm 
Can you show me a  `node_modules/react-native/Libraries/Components/TextInput/TextInput.js` file?

**Comment by marcorm** [comment]
> @marcorm
> Can you show me a `node_modules/react-native/Libraries/Components/TextInput/TextInput.js` file?

Hi @retyui , sure. Here it is:
https://pastebin.com/nFU0fURJ

**Comment by retyui** [comment]
thanks a lot
Oh, Now  I see the problem (
To fix it you can run:
```
node node_modules/react-native-confirmation-code-field/path-rn-62.js
```

**Comment by YuraTaranov** [comment]
@retyui Hello, I copied the code from the example, but when you click on any input, the focus is not set and it is impossible to delete the data, react native 63.3, tried to wrap the input in a view with a fixed height like the input and set the autofocus prop, it didn’t help, I don’t know what else to do, help please, issue is on android and ios

**Comment by retyui** [comment]
the main problem is that I use an "a temporary" hack (with was removed in `react-native@0.64+`) to get an event when a user presses on `TextInput`

to apply required changes (with will add `onPress` event listen on `TextInput` component) you can run the next command: 
```tsx
node node_modules/react-native-confirmation-code-field/path-rn-62.js
```

and restart a Metro server:

```bash
npx react-native start --reset-cache
```
