### ISSUE TITLE
Not working on ios

### ISSUE THREAD

**Issue by makarkotlov** [retyui/react-native-confirmation-code-field#80]
Autofocus and onFulfill not working on ios. Fresh build. It shows the warning "-[RCTRootView cancelTouches] is deprecated and will be deleted soon". Android is working well. RN 0.61.2. Workaround is to add import 'react-native-gesture-handler' on top of index.js. onFulfill is working, but autofocus is still not. When manually focusing it show the same warning

**Comment by retyui** [comment]
@makarkotlov 
Can you record a video to demonstrate a problem, or share the code?

**Comment by makarkotlov** [comment]
Thank you @retyui! I've found the issue and it's related to me using react-native-confirmation-code-input in one place instead of react-native-confirmation-code-field
