### ISSUE TITLE
Wrong 'onTextChange' function name

### ISSUE THREAD

**Issue by samthui** [retyui/react-native-confirmation-code-field#81]
In ```ConfirmationCodeInput.js```, method ```handlerOnTextChange```, the methodName to be inherited must be ```onChangeText```, not ```onTextChange```.
I think this only is a typo coz ```inputProps``` is of type ```ReactNative.TextInputProps```, so it only has ```onChangeText```, not ```onTextChange```.

**Comment by retyui** [comment]
fixed on https://github.com/retyui/react-native-confirmation-code-field/blob/master/CHANGELOG.md#410
