### ISSUE TITLE
Why onCodeChange was deleted?

### ISSUE THREAD

**Issue by makarkotlov** [retyui/react-native-confirmation-code-field#83]
Why onCodeChange was deleted? Now to mimic it's behavior I must use ref. I'm using ^4.1.0. onChangeText that was added in 4.1.0 is not working. @retyi Look what you've done to my code

![image](https://user-images.githubusercontent.com/32848434/67026945-6e5f7b00-f111-11e9-9df9-865817c17214.png)

**Comment by retyui** [comment]
Just read changelog:
https://github.com/retyui/react-native-confirmation-code-field/blob/master/CHANGELOG.md

**Comment by retyui** [comment]
@makarkotlov 
I’m not sure I understand what kind of method the `onCodeChange`

And the screenshot you proposed does not reflect the essence of the problem
