### ISSUE TITLE
How can I control onFulfill ?

### ISSUE THREAD

**Issue by yasir-netlinks** [retyui/react-native-confirmation-code-field#84]
The default behavior when the user is done with the input of code, it executes `onFulfill` but what if I don't want this behavior and rather wait for the user to press a button and then run `onFulfill` function? can I do that!

**Comment by retyui** [comment]
Yes, you can

**Comment by yasir-netlinks** [comment]
@retyui could you please show the code where I'm able to do that, cuz I can't seem to find the prop

**Comment by retyui** [comment]
You can ignore all on press events on button until i Fulfill would called

**Comment by yasir-netlinks** [comment]
@retyui I think you didn't get what I meant, I don't want the `onFulfill` to run automatically after input is populated, but rather run the `onFulfill` on a button press (no automatically)

**Comment by retyui** [comment]
Button this component don't have any buttons

**Comment by retyui** [comment]
@yasir-netlinks  So...
