### ISSUE TITLE
[error] Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by tsukiaka** [retyui/react-native-confirmation-code-field#86]
I have this error with react-native@0.58.4 and the plugin is version 3.4.1. I find out after some debug that it was coming from this component. It was working properly before I don't really know what happened. It's seems to be only on Android.

Does someone has the same issue?

Edit: It's weird, when I use the remote live reload, it's working properly

**Comment by retyui** [comment]
@tsukiaka 
Can you provide an example of you's code or create demo repo to demonstrate problem, because I tried to reproduce it on `RN@0.58.0 + react-native-confirmation-code-field@3.4.1` and it work fine

**Comment by tsukiaka** [comment]
I think it's working, actually the problem is after I try to bundle my app using: 

react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

After that, it's not working properly, maybe a problem in my end, I will investigate.

**Comment by tsukiaka** [comment]
I fixed it by using this babel conf:

`module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [
    [
      "@babel/plugin-transform-spread",
      {
        "loose": true
      }
    ]
  ],`

But now, when I type a code on android, all the code go in the first cell.
