### ISSUE TITLE
How to paste code in CodeInput with animation.

### ISSUE THREAD

**Issue by Thronie** [retyui/react-native-confirmation-code-field#87]

**Comment by Thronie** [comment]
I read the code from the sms and want to paste it in CodeInput automatically. How can I do that?

**Comment by retyui** [comment]
@Thronie Hi

**Comment by retyui** [comment]
You can see an example in readme 
https://github.com/retyui/react-native-confirmation-code-field#how-paste-or-clear-code

**Comment by Thronie** [comment]
@retyui I want with animation how to do that.

**Comment by retyui** [comment]
It will be the same, nothing special
