### ISSUE TITLE
Add documentation for manual verification pattern

### ISSUE THREAD

**Issue by tomsotte** [retyui/react-native-confirmation-code-field#88]
A missing pattern on the documentation that I believe could be common case is when you have a button for manual code confirmation.
The "Verify" button might be disabled initially and enabled when the use fulfill the code. But if the user changes the code for any reason you need to determine when the user has edited the code. You have to re-set the button to a disabled state until the code is fulfilled again.

I've done it this way, as I assume that whenever the user re-focus the input the previous code gets partially deleted and the confirmation button should be disabled.

```jsx
const [canVerify, setCanVerify] = useState(false);

<CodeInput
  blurOnSubmit={true}
  inputProps={{
    onFocus: () => setCanVerify(false),
  }}
  onFulfill={() => setCanVerify(true)}
/>
<Button
  title="Verify"
  disabled={!canVerify}
/>
```

**Comment by retyui** [comment]
@tomsotte 
Try this:
```js
const [canVerify, setCanVerify] = useState(false);

const CODE_LENGTH = 5;

<CodeInput
    blurOnSubmit
    codeLength={CODE_LENGTH}
    inputProps={{
      onChangeText: code => setCanVerify(code.length === CODE_LENGTH),
    }}
/>

<Button
  title="Verify"
  disabled={!canVerify}
/>
```

**Comment by tomsotte** [comment]
Thanks, I see that's a better implementation as I don't have to make any assumption on the focus behaviour. I think you might make `onChangeText` as a prop for CodeInput or just add this in the documentation in the inputProps section.
