### ISSUE TITLE
Height between Code and Underline

### ISSUE THREAD

**Issue by samitha9125** [retyui/react-native-confirmation-code-field#9]
I just tried to reduce the height between Code we type and Underline which happens using `variant = 'border-b'` using  `getInputStyle={this.getInputStyle}` as you have mentioned. But it does not reduce the gap. Can I have a method suggestion to reduce the gap ? 

**What I get**
<img width="271" alt="screen shot 2018-08-30 at 9 47 50 am" src="https://user-images.githubusercontent.com/36798097/44829433-82f56100-ac3a-11e8-827c-4131de747e15.png">

**What I want**
<img width="302" alt="screen shot 2018-08-30 at 9 48 57 am" src="https://user-images.githubusercontent.com/36798097/44829435-838df780-ac3a-11e8-971b-531aad973813.png">

**Comment by retyui** [comment]
@samitha9125 
You can change style for `lineHeigth` and `heigth` for that would get the desired result
Example: https://snack.expo.io/@retyui/calm-strawberries
