### ISSUE TITLE
 Can't check onChangeText here?

### ISSUE THREAD

**Issue by 97thjingba** [retyui/react-native-confirmation-code-field#92]
just as the title, can not check the input value anytime ？

**Comment by retyui** [comment]
Try:
```js
import React, { Component } from 'react';
import CodeInput from 'react-native-confirmation-code-field';

class App extends Component {
  handlerOnFulfill = code => console.log(code);

  render() {
    return <CodeInput 
       inputProps={ {onTextChange: text => console.log(text) } }
       onFulfill={this.handlerOnFulfill}
    />;
  }
}
```

**Comment by 97thjingba** [comment]
thanke you！

**Comment by saidhappy010** [comment]
I used the above code, it works, but the inputProps props does not display the input that I insert.
how could we resolve this issue ?.
thanks.

**Comment by 97thjingba** [comment]
I do not know what you mean .? @saidhappy010

**Comment by retyui** [comment]
@saidhappy010 
In new version I rewrite this behavior
You can use `next` tag
```
yarn add react-native-confirmation-code-field@next
```
But I need time to update documentation

**Comment by saidhappy010** [comment]
@retyui .Please could you give me an example
