### ISSUE TITLE
Clearing on Previous Pin Values when I clicked the particular pin

### ISSUE THREAD

**Issue by tharun208** [retyui/react-native-confirmation-code-field#95]
Let's say, I have a 4 data filled pin, When I clicked on the 3nd pin , the pin data (1,2,3) get's cleared and this is not supposed to happen.Is there a workaround possible ?

**Comment by retyui** [comment]
@tharun208 Can you create a demo to demonstrate a problem?

**Comment by tharun208** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14926492/72250173-fc6bd480-3620-11ea-9e4b-83dfd3e538c0.gif)

I clicked on a particular index and it is clearing from the last to the particular index.

This is why because we are a maintaining your local state for input value's as a string, we need to convert it to an array of strings

**Comment by retyui** [comment]
Oh I see
This behavior by default and cannot be configured

**Comment by DwCleb** [comment]
@retyui We have the possibility to open a PR to change this behavior?

**Comment by retyui** [comment]
@DwCleb 
PRs welcome!
