### ISSUE TITLE
change TextInput style

### ISSUE THREAD

**Issue by cybercoder** [retyui/react-native-confirmation-code-field#96]
```javascript
<CodeInput 
       inputProps={ {onTextChange: text => console.log(text) , style: {fontFamily: 'x', fontSize:50} }
...
```
fontFamily and fontSize don't change, Did i pass them wrong way?

**Comment by retyui** [comment]
Please use a [cellProps](https://github.com/retyui/react-native-confirmation-code-field/blob/master/docs/API.md#cellprops-textinputprops--index-number-isfocused-boolean-hasvalue-boolean--textinputprops)
