### ISSUE TITLE
Add a prop for customizing cursor symbol

### ISSUE THREAD

**Issue by ianidi** [retyui/react-native-confirmation-code-field#97]
Thank you for library, amazing work.

The title says it all. Currently cursor is |. In my usecase I would like to completely disable cursor, e.g. pass a prop like cursorSymbol={""}.

**Comment by ianidi** [comment]
The same to customizing cursor style properties.

**Comment by retyui** [comment]
You can create own wrapper `<CustomCodeInput/>` and rewrite `.renderCursor()` method to implement behavior described above
 
```js
import CodeInput from 'react-native-confirmation-code-field';

class CustomCodeInput extends CodeInput {
  renderCursor() {
    return null;
  }
}
```
