### ISSUE TITLE
Cursor flickering on first field

### ISSUE THREAD

**Issue by zihandev** [retyui/react-native-confirmation-code-field#99]
While trying to edit some other field (on press of 4th field out of 6 field code), the cursor flickers for a second on 1st field and then focuses on 4th field. Tried to manually focus on the clicked input field but did not work. Also while clicking on the focused field again, there are two cursors appearing on screen.
Issue can be seen on snack expo link as well. 
https://snack.expo.io/@retyui/demo-for-react-native-confirmation-code-field

Regards,
Zihan

**Comment by retyui** [comment]
@zihandev It should be fixed in a new release 5.0.x

**Comment by zihandev** [comment]
Hey yeah seems to be working now ! Great job. Just had one query, I was facing a bit of difficulty trying to clear the inputs on submit, I cleared inputs passing a reference to the codefiled component in previous version, which doesn't seem to be working with latest one. Is there an easier way to clear the inputs ? 

Regards, 
Zihan

**Comment by retyui** [comment]
@zihandev 

After invoke `.clear()` TextInput doesn't call onChange handler
You should manually set empty value:

```js
const [value, setValue] = useState('');
const clearValue = () => setValue('');

return <CodeField
    value={value}
    onChangeText={setValue}
    // ...
/>;

```

**Comment by zihandev** [comment]
Yup working fine now ! Passed the reference through props and manually cleared the fields. Thanks a ton! 
<CodeField
     ref={props.refs}
     clear={() => setValue('')}
//...
/>
